"""One real call of each built-in SQL function DataLab allows (sqlcheck.ORACLE_FUNCTIONS).

Every name on the list needs a call here: the unit tests check that the SQL check
accepts it, and the Oracle tests check, on the synthetic database, that no
same-named function can take the built-in's place.

Calls run against ROWS: ten rows with a number x, a 0/1 group g, and a string s.
"""

ROWS = "(SELECT LEVEL AS x, MOD(LEVEL, 2) AS g, 'a' AS s FROM DUAL CONNECT BY LEVEL <= 10)"

# Closes a subquery that must return one row.
FIRST = "ORDER BY 1 FETCH FIRST 1 ROWS ONLY"

SAMPLE_CALLS = {
    "REGEXP_LIKE": "CASE WHEN REGEXP_LIKE('abc', '^a') THEN 1 END",
    "JSON_EXISTS": "CASE WHEN JSON_EXISTS('{\"a\":1}', '$.a') THEN 1 END",
    "ABS": "ABS(-2)",
    "ACOS": "ACOS(0.5)",
    "ADD_MONTHS": "ADD_MONTHS(DATE '2025-01-31',1)",
    "APPROX_COUNT_DISTINCT": "APPROX_COUNT_DISTINCT(1)",
    "APPROX_MEDIAN": "APPROX_MEDIAN(3)",
    "APPROX_PERCENTILE": "APPROX_PERCENTILE(0.5) WITHIN GROUP (ORDER BY 3)",
    "ASCII": "ASCII('A')",
    "ASCIISTR": "ASCIISTR('abc')",
    "ASIN": "ASIN(0.5)",
    "ATAN": "ATAN(1)",
    "ATAN2": "ATAN2(1,2)",
    "AVG": "AVG(2)",
    "BIN_TO_NUM": "BIN_TO_NUM(1,0,1)",
    "BITAND": "BITAND(6,3)",
    "CAST": "CAST('1' AS NUMBER)",
    "CEIL": "CEIL(1.2)",
    "CHR": "CHR(65)",
    "COALESCE": "COALESCE(NULL,1)",
    "COMPOSE": "COMPOSE('a')",
    "CONCAT": "CONCAT('a','b')",
    "CONVERT": "CONVERT('abc','US7ASCII')",
    "CORR": "CORR(1,2)",
    "CORR_K": "CORR_K(x, g)",
    "CORR_S": "CORR_S(x, g)",
    "COS": "COS(1)",
    "COSH": "COSH(1)",
    "COUNT": "COUNT(1)",
    "COVAR_POP": "COVAR_POP(1,2)",
    "COVAR_SAMP": "COVAR_SAMP(1,2)",
    "CUME_DIST": "CUME_DIST() OVER (ORDER BY 1)",
    "CURRENT_DATE": "TO_CHAR(CURRENT_DATE, 'YYYY')",
    "CURRENT_TIMESTAMP": "TO_CHAR(CURRENT_TIMESTAMP, 'YYYY')",
    "DECODE": "DECODE(1,1,'a','b')",
    "DECOMPOSE": "DECOMPOSE('a')",
    "DENSE_RANK": "DENSE_RANK() OVER (ORDER BY 1)",
    "EXP": "EXP(1)",
    "EXTRACT": "EXTRACT(YEAR FROM DATE '2025-01-01')",
    "FIRST_VALUE": "FIRST_VALUE(1) OVER (ORDER BY 1)",
    "FLOOR": "FLOOR(1.7)",
    "FROM_TZ": "FROM_TZ(TIMESTAMP '2025-01-01 10:00:00','-05:00')",
    "GREATEST": "GREATEST(1,3,2)",
    "GROUPING": f"(SELECT GROUPING(g) FROM {ROWS} GROUP BY ROLLUP(g) {FIRST})",
    "GROUPING_ID": f"(SELECT GROUPING_ID(g) FROM {ROWS} GROUP BY ROLLUP(g) {FIRST})",
    "GROUP_ID": f"(SELECT GROUP_ID() FROM {ROWS} GROUP BY g {FIRST})",
    "HEXTORAW": "HEXTORAW('41')",
    "INITCAP": "INITCAP('ab cd')",
    "INSTR": "INSTR('abc','b')",
    "INSTRB": "INSTRB('abc','b')",
    "INSTRC": "INSTRC('abc', 'b')",
    "JSON_ARRAY": "JSON_ARRAY(1,2)",
    "JSON_ARRAYAGG": "JSON_ARRAYAGG(x)",
    "JSON_OBJECT": "JSON_OBJECT('a' VALUE 1)",
    "JSON_OBJECTAGG": "JSON_OBJECTAGG(KEY s VALUE x)",
    "JSON_QUERY": "JSON_QUERY('{\"a\":[1]}','$.a')",
    "JSON_SERIALIZE": "JSON_SERIALIZE('{\"a\":1}')",
    "JSON_VALUE": "JSON_VALUE('{\"a\":1}','$.a')",
    "LAG": "LAG(1) OVER (ORDER BY 1)",
    "LAST_DAY": "LAST_DAY(DATE '2025-02-10')",
    "LAST_VALUE": "LAST_VALUE(1) OVER (ORDER BY 1)",
    "LEAD": "LEAD(1) OVER (ORDER BY 1)",
    "LEAST": "LEAST(1,3,2)",
    "LENGTH": "LENGTH('abc')",
    "LENGTHB": "LENGTHB('abc')",
    "LENGTHC": "LENGTHC('abc')",
    "LISTAGG": "LISTAGG('a', ',') WITHIN GROUP (ORDER BY 1)",
    "LN": "LN(2)",
    "LNNVL": "CASE WHEN LNNVL(1=2) THEN 'y' END",
    "LOCALTIMESTAMP": "TO_CHAR(LOCALTIMESTAMP, 'YYYY')",
    "LOG": "LOG(10,100)",
    "LOWER": "LOWER('AB')",
    "LPAD": "LPAD('1',3,'0')",
    "LTRIM": "LTRIM('  a')",
    "MAX": "MAX(1)",
    "MEDIAN": "MEDIAN(3)",
    "MIN": "MIN(1)",
    "MOD": "MOD(7,3)",
    "MONTHS_BETWEEN": "MONTHS_BETWEEN(DATE '2025-03-01', DATE '2025-01-01')",
    "NANVL": "NANVL(1,0)",
    "NCHR": "NCHR(65)",
    "NEW_TIME": "NEW_TIME(DATE '2025-01-01','EST','PST')",
    "NEXT_DAY": "NEXT_DAY(DATE '2025-01-01','MONDAY')",
    "NLSSORT": "NLSSORT('a')",
    "NLS_INITCAP": "NLS_INITCAP('ab')",
    "NLS_LOWER": "NLS_LOWER('AB')",
    "NLS_UPPER": "NLS_UPPER('ab')",
    "NTH_VALUE": "NTH_VALUE(1,1) OVER (ORDER BY 1)",
    "NTILE": "NTILE(4) OVER (ORDER BY 1)",
    "NULLIF": "NULLIF(1,2)",
    "NUMTODSINTERVAL": "NUMTODSINTERVAL(2,'HOUR')",
    "NUMTOYMINTERVAL": "NUMTOYMINTERVAL(2,'MONTH')",
    "NVL": "NVL(NULL,1)",
    "NVL2": "NVL2(NULL,1,2)",
    "ORA_HASH": "ORA_HASH('abc')",
    "PERCENTILE_CONT": "PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY 3)",
    "PERCENTILE_DISC": "PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY 3)",
    "PERCENT_RANK": "PERCENT_RANK() OVER (ORDER BY 1)",
    "POWER": "POWER(2,3)",
    "RANK": "RANK() OVER (ORDER BY 1)",
    "RATIO_TO_REPORT": "RATIO_TO_REPORT(1) OVER ()",
    "RAWTOHEX": "RAWTOHEX(HEXTORAW('41'))",
    "RAWTONHEX": "RAWTONHEX(HEXTORAW('41'))",
    "REGEXP_COUNT": "REGEXP_COUNT('abab','b')",
    "REGEXP_INSTR": "REGEXP_INSTR('abc','b')",
    "REGEXP_REPLACE": "REGEXP_REPLACE('abc','b','x')",
    "REGEXP_SUBSTR": "REGEXP_SUBSTR('abc','b')",
    "REGR_AVGX": "REGR_AVGX(1,2)",
    "REGR_AVGY": "REGR_AVGY(x, g)",
    "REGR_COUNT": "REGR_COUNT(1,2)",
    "REGR_INTERCEPT": "REGR_INTERCEPT(1,2)",
    "REGR_R2": "REGR_R2(1,2)",
    "REGR_SLOPE": "REGR_SLOPE(1,2)",
    "REGR_SXX": "REGR_SXX(1,2)",
    "REGR_SXY": "REGR_SXY(x, g)",
    "REGR_SYY": "REGR_SYY(x, g)",
    "REMAINDER": "REMAINDER(7,3)",
    "REPLACE": "REPLACE('abc','b','x')",
    "ROUND": "ROUND(1.26,1)",
    "ROW_NUMBER": "ROW_NUMBER() OVER (ORDER BY 1)",
    "RPAD": "RPAD('1',3,'0')",
    "RTRIM": "RTRIM('a  ')",
    "SIGN": "SIGN(-3)",
    "SIN": "SIN(1)",
    "SINH": "SINH(1)",
    "SOUNDEX": "SOUNDEX('smith')",
    "SQRT": "SQRT(4)",
    "STANDARD_HASH": "STANDARD_HASH('abc','SHA256')",
    "STATS_BINOMIAL_TEST": "STATS_BINOMIAL_TEST(g, 1, 0.5, 'TWO_SIDED_PROB')",
    "STATS_CROSSTAB": "STATS_CROSSTAB(g, s, 'CHISQ_SIG')",
    "STATS_F_TEST": "STATS_F_TEST(g, x, 'TWO_SIDED_SIG')",
    "STATS_KS_TEST": "STATS_KS_TEST(g, x, 'SIG')",
    "STATS_MODE": "STATS_MODE(1)",
    "STATS_MW_TEST": "STATS_MW_TEST(g, x, 'TWO_SIDED_SIG')",
    "STATS_ONE_WAY_ANOVA": "STATS_ONE_WAY_ANOVA(g, x, 'SIG')",
    "STATS_T_TEST_INDEP": "STATS_T_TEST_INDEP(g, x)",
    "STATS_T_TEST_INDEPU": "STATS_T_TEST_INDEPU(g, x)",
    "STATS_T_TEST_ONE": "STATS_T_TEST_ONE(x, 5)",
    "STATS_T_TEST_PAIRED": "STATS_T_TEST_PAIRED(x, g)",
    "STATS_WSR_TEST": "STATS_WSR_TEST(x, g)",
    "STDDEV": "STDDEV(3)",
    "STDDEV_POP": "STDDEV_POP(3)",
    "STDDEV_SAMP": "STDDEV_SAMP(3)",
    "SUBSTR": "SUBSTR('abc',2,1)",
    "SUBSTRB": "SUBSTRB('abc',2,1)",
    "SUBSTRC": "SUBSTRC('abc',2,1)",
    "SUM": "SUM(1)",
    "SYSDATE": "TO_CHAR(SYSDATE, 'YYYY')",
    "SYSTIMESTAMP": "TO_CHAR(SYSTIMESTAMP, 'YYYY')",
    "SYS_CONNECT_BY_PATH": (
        f"(SELECT SYS_CONNECT_BY_PATH(x, '/') FROM {ROWS} CONNECT BY PRIOR x = x - 1 {FIRST})"
    ),
    "SYS_EXTRACT_UTC": "SYS_EXTRACT_UTC(TIMESTAMP '2025-01-01 10:00:00 -05:00')",
    "TAN": "TAN(1)",
    "TANH": "TANH(1)",
    "TO_BINARY_DOUBLE": "TO_BINARY_DOUBLE('1.5')",
    "TO_BINARY_FLOAT": "TO_BINARY_FLOAT('1.5')",
    "TO_CHAR": "TO_CHAR(DATE '2025-01-01','YYYY')",
    "TO_CLOB": "TO_CLOB('abc')",
    "TO_DATE": "TO_DATE('2025-01-01','YYYY-MM-DD')",
    "TO_DSINTERVAL": "TO_DSINTERVAL('1 02:00:00')",
    "TO_MULTI_BYTE": "TO_MULTI_BYTE('a')",
    "TO_NCHAR": "TO_NCHAR('abc')",
    "TO_NCLOB": "TO_NCLOB('abc')",
    "TO_NUMBER": "TO_NUMBER('12')",
    "TO_SINGLE_BYTE": "TO_SINGLE_BYTE('a')",
    "TO_TIMESTAMP": "TO_TIMESTAMP('2025-01-01','YYYY-MM-DD')",
    "TO_TIMESTAMP_TZ": "TO_TIMESTAMP_TZ('2025-01-01 10:00 -05:00','YYYY-MM-DD HH24:MI TZH:TZM')",
    "TO_YMINTERVAL": "TO_YMINTERVAL('01-02')",
    "TRANSLATE": "TRANSLATE('abc','b','x')",
    "TRIM": "TRIM(' a ')",
    "TRUNC": "TRUNC(1.9)",
    "TZ_OFFSET": "TZ_OFFSET('US/Eastern')",
    "UNISTR": "UNISTR('abc')",
    "UPPER": "UPPER('ab')",
    "VALIDATE_CONVERSION": "VALIDATE_CONVERSION('12' AS NUMBER)",
    "VARIANCE": "VARIANCE(3)",
    "VAR_POP": "VAR_POP(3)",
    "VAR_SAMP": "VAR_SAMP(3)",
    "VSIZE": "VSIZE('abc')",
    "WIDTH_BUCKET": "WIDTH_BUCKET(5,0,10,4)",
}
