"""A person's own edits in the Pipelines tab: Edit manually, New file, and
Edit before accepting. The same check, tests and Save & share as an agent's
proposal (test_pipelines.py, whose GitHub stand-in and test container these
use), committed as the person with a DataLab-Edit trailer.
"""

from __future__ import annotations

import time

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from datalab import db
from datalab.api.pipelines import PipelineServices, build_pipelines_router
from datalab.config import Settings
from datalab.pipelines import edits as edits_module
from datalab.repos.git import GitError, Identity, name_problem
from datalab.sessions.manager import SessionManager
from datalab.sessions.store import ConversationStore
from datalab.sessions.tokens import SessionTokens
from tests.kb_fixtures import git
from tests.test_pipelines import NEW_STEPS, STEPS_R, FakeSandbox, Lab, conversation, synced, turn
from tests.test_pipelines import lab as lab  # the fixture

STEPS = "ihsDataR/R/steps.R"
ROXYGEN_RD = "% Generated by roxygen2: do not edit by hand\n\\name{weekly_steps}\n"


def start(lab: Lab, path: str = STEPS, *, new: bool = False) -> dict:
    response = lab.client.post("/api/pipelines/edits", json={"path": path, "new": new})
    assert response.status_code == 200, response.text
    return response.json()


def keep(lab: Lab, edit: dict, files: dict[str, str | None]) -> dict:
    response = lab.client.put(
        f"/api/pipelines/edits/{edit['id']}", json={"files": files, "version": edit["updated_at"]}
    )
    assert response.status_code == 200, response.text
    return response.json()


def settled(lab: Lab, edit_id: str) -> dict:
    """The edit once its tests or its save have finished (they run in the background)."""
    for _ in range(200):
        found = lab.client.get(f"/api/pipelines/edits/{edit_id}").json()
        test = found["test"]
        if found["status"] != "saving" and not (test and test["status"] == "running"):
            return found
        time.sleep(0.05)
    raise AssertionError("still going")


def share(lab: Lab, edit: dict, confirmed: list[str] | None = None) -> dict:
    response = lab.client.post(
        f"/api/pipelines/edits/{edit['id']}/share",
        json={"confirmed": confirmed or [], "version": edit["updated_at"]},
    )
    assert response.status_code == 200, response.text
    return settled(lab, edit["id"])


def test_a_persons_edit_is_kept_on_this_computer_then_shared_like_a_proposal(lab, monkeypatch):
    synced(lab)
    before = lab.remote.head()
    edit = start(lab)
    assert edit["status"] == "draft" and edit["base"] == before
    assert edit["files"][0] | {"diff": ""} == {
        "path": STEPS, "text": STEPS_R, "new": False, "before": STEPS_R, "diff": "",
        "upstream_changed": False, "theirs": None, "theirs_state": "text", "source_note": None,
    }  # fmt: skip
    # The file view knows it can be edited, and finds this draft.
    shown = lab.client.get(f"/api/pipelines/files/{STEPS}").json()
    assert (shown["editable"], shown["source_note"], shown["draft"]) == (True, None, edit["id"])
    # One open edit per file: opening it again finds this one.
    assert start(lab)["id"] == edit["id"]

    kept = keep(lab, edit, {STEPS: NEW_STEPS})
    assert kept["files"][0]["text"] == NEW_STEPS and "+  x * 7" in kept["files"][0]["diff"]
    assert lab.remote.head() == before  # a draft goes nowhere
    # Kept in DataLab's database: another start (a reload) finds the same text.
    assert start(lab)["files"][0]["text"] == NEW_STEPS
    # An older version of the draft (another window) doesn't overwrite it.
    stale = lab.client.put(
        f"/api/pipelines/edits/{edit['id']}", json={"files": {STEPS: "x"}, "version": "old"}
    )
    assert stale.status_code == 409

    shares = []
    real = edits_module.share.save_and_share

    async def spy(clone, request, tester):
        shares.append(request)
        return await real(clone, request, tester)

    monkeypatch.setattr(edits_module.share, "save_and_share", spy)
    done = share(lab, kept)
    assert done["status"] == "saved", done
    [request] = shares
    assert request.by_person and request.strict
    assert request.trailers == (("DataLab-Edit", edit["id"]),)
    assert request.files == {STEPS: NEW_STEPS.encode()}
    assert request.workflows is not None  # the workflow check, as for a proposal
    assert lab.remote.show(STEPS) == NEW_STEPS.rstrip("\n")
    assert done["commit"] == lab.remote.head()
    [line] = lab.remote.log("%an <%ae>|%s")[:1]
    assert line == "Yu Fang <42+yfang@users.noreply.github.com>|Pipelines: steps.R"
    message = git("log", "-1", "--format=%B", "main", cwd=lab.remote.bare)
    assert "Edited by hand and saved in DataLab by Yu Fang (@yfang)." in message
    assert f"DataLab-Edit: {edit['id']}" in message
    assert f"DataLab-Tests: {done['result']['test']}" in message
    assert len(lab.sandbox.steps) == 1  # the tests ran before the push
    # Done: the file has no open edit, and a new one starts from the shared version.
    assert lab.client.get(f"/api/pipelines/files/{STEPS}").json()["draft"] is None
    again = start(lab)
    assert again["id"] != edit["id"] and again["files"][0]["text"] == NEW_STEPS


def test_the_tests_run_on_the_persons_files_in_the_container(lab):
    synced(lab)
    edit = keep(lab, start(lab), {STEPS: NEW_STEPS})
    response = lab.client.post(f"/api/pipelines/edits/{edit['id']}/tests")
    assert response.status_code == 200, response.text
    done = settled(lab, edit["id"])
    assert done["test"]["status"] == "passed" and done["test"]["tests"] == 3
    [tree] = lab.sandbox.trees
    assert tree[STEPS] == NEW_STEPS
    # Failing tests stop Save & share; nothing is shared.
    before = lab.remote.head()
    lab.sandbox.failing = 1
    edit = keep(lab, done, {STEPS: NEW_STEPS + "\n"})
    failed = share(lab, edit)
    assert failed["status"] == "tests_failed" and lab.remote.head() == before


def test_the_check_is_the_proposals_inline_and_on_share(lab):
    synced(lab)
    fixture = "ihsDataR/tests/testthat/fixtures/ids.csv"
    edit = start(lab, fixture, new=True)
    assert edit["files"][0] | {"diff": ""} == {
        "path": fixture, "text": "", "new": True, "before": None, "diff": "",
        "upstream_changed": False, "theirs": None, "theirs_state": "deleted", "source_note": None,
    }  # fmt: skip
    # What's in the editor now, not yet kept: findings with their lines.
    text = "participant_id,date\n1001,2019-03-02\n"
    found = lab.client.post(
        f"/api/pipelines/edits/{edit['id']}/check", json={"path": fixture, "text": text}
    ).json()["findings"]
    assert {(f["rule"], f["line"]) for f in found} >= {("id_columns", 1), ("date_near_number", 2)}
    hook = STEPS_R + ".onLoad <- function(libname, pkgname) NULL\n"
    other = start(lab)
    code = lab.client.post(
        f"/api/pipelines/edits/{other['id']}/check", json={"path": STEPS, "text": hook}
    ).json()["findings"]
    assert [(f["rule"], f["severity"], f["line"]) for f in code] == [("load_hook", "code", 4)]
    # A pipeline file that wouldn't load is an error, as in a proposal.
    spec = start(lab, "ihsDataR/inst/pipelines/steps/pipeline.yaml", new=True)
    bad = lab.client.post(
        f"/api/pipelines/edits/{spec['id']}/check",
        json={"path": spec["files"][0]["path"], "text": "name: other\nreads: []\noutputs: {}\n"},
    ).json()["findings"]
    assert bad and all(f["rule"] == "pipeline" and f["severity"] == "error" for f in bad)

    # Kept and shared: the data findings wait for the person, before the tests.
    edit = keep(lab, edit, {fixture: text})
    assert {f["rule"] for f in edit["findings"]} >= {"data_file", "id_columns"}
    stopped = share(lab, edit)
    assert stopped["status"] == "check_failed" and lab.sandbox.steps == []
    ids = [f["id"] for f in stopped["result"]["findings"]]
    saved = share(lab, stopped, ids)
    assert saved["status"] == "saved", saved
    assert lab.remote.show(fixture) == text.rstrip("\n")


def test_what_cant_be_edited_says_why(lab):
    lab.remote.write(
        {
            "ihsDataR/man/weekly_steps.Rd": ROXYGEN_RD.encode(),
            "ihsDataR/NAMESPACE": b"# Generated by roxygen2: do not edit by hand\n",
        },
        "Document",
    )
    synced(lab)
    for path, words in (
        ("ihsDataR/man/weekly_steps.Rd", "#' comments"),
        ("ihsDataR/NAMESPACE", "@export"),
        ("AGENTS.md", "there to read"),
        ("reference/2024/Steps_2024.R", "there to read"),
    ):
        shown = lab.client.get(f"/api/pipelines/files/{path}").json()
        assert shown["editable"] is False and words in shown["source_note"], path
        refused = lab.client.post("/api/pipelines/edits", json={"path": path})
        assert refused.status_code == 409, path
    refused = lab.client.post("/api/pipelines/edits", json={"path": ".github/workflows/ci.yml"})
    assert refused.status_code == 409 and ".github" in refused.json()["detail"]


def test_new_files_only_where_the_repo_takes_them(lab):
    synced(lab)
    for path in (
        "reference/new.R",  # outside ihsDataR/ and workflows/
        ".github/workflows/new.yml",
        "workflows/deep/new.yaml",  # workflow files are workflows/<name>.yaml
        "ihsDataR/R/tool.exe",  # not a text file's kind
        "ihsDataR/R/STEPS.R",  # clashes with steps.R on Windows and Mac
        "ihsDataR/R",  # a folder
        "ihsDataR/R/../../x.R",
        # In a "folder" that's a file: git would drop the file, silently.
        "ihsDataR/tests/testthat/test-steps.R/extra.R",
        "ihsDataR/DESCRIPTION/x.R",
        "ihsDataR/description/x.R",
        "ihsDataR/r/new.R",  # beside ihsDataR/R/, differing only in case
        "ihsDataR/R/" + "n" * 101 + ".R",  # a name too long for some computers
    ):
        response = lab.client.post("/api/pipelines/edits", json={"path": path, "new": True})
        assert response.status_code == 409, path
    folder = lab.client.post(
        "/api/pipelines/edits", json={"path": "ihsDataR/DESCRIPTION/x.R", "new": True}
    )
    assert "ihsDataR/DESCRIPTION is a file, not a folder" in folder.json()["detail"]
    # One open edit per file, whatever the case of its name.
    start(lab, "ihsDataR/R/new.R", new=True)
    twin = lab.client.post("/api/pipelines/edits", json={"path": "ihsDataR/R/NEW.R", "new": True})
    assert twin.status_code == 409 and "differing only in case" in twin.json()["detail"]
    taken = lab.client.post("/api/pipelines/edits", json={"path": STEPS, "new": True})
    assert taken.status_code == 409
    made = start(lab, "workflows/monthly.yaml", new=True)
    assert made["files"][0]["new"] is True
    # A file an edit doesn't have can't be slipped into it.
    sneaky = lab.client.put(
        f"/api/pipelines/edits/{made['id']}",
        json={"files": {"AGENTS.md": "x"}, "version": made["updated_at"]},
    )
    assert sneaky.status_code == 409


def test_github_moving_on_is_a_conflict_to_resolve_nothing_overwritten(lab):
    synced(lab)
    three = "a <- 1\nb <- 2\nc <- 3\n"
    lab.remote.write({STEPS: three.encode()}, "Three lines")
    synced(lab)
    edit = keep(lab, start(lab), {STEPS: "a <- 10\nb <- 2\nc <- 3\n"})
    theirs = lab.remote.write({STEPS: b"a <- 1\nb <- 2\nc <- 30\n"}, "Someone else")
    # Not synced yet: Save & share fetches, and stops rather than merge.
    stopped = share(lab, edit)
    assert stopped["status"] == "conflict", stopped
    assert stopped["result"]["conflicts"] == [STEPS] and lab.remote.head() == theirs
    assert stopped["upstream_changed"]
    assert stopped["files"][0]["theirs"] == "a <- 1\nb <- 2\nc <- 30\n"
    assert stopped["files"][0]["before"] == three
    # Reapplied: the two changes merge, onto GitHub's version.
    moved = lab.client.post(
        f"/api/pipelines/edits/{edit['id']}/reapply", json={"version": stopped["updated_at"]}
    ).json()
    assert moved["merged"] == {}
    assert moved["edit"]["files"][0]["text"] == "a <- 10\nb <- 2\nc <- 30\n"
    assert moved["edit"]["base"] == theirs and not moved["edit"]["upstream_changed"]
    # Changed where someone else also did: the overlap is shown, and the person writes it.
    edit = keep(lab, moved["edit"], {STEPS: "a <- 11\nb <- 2\nc <- 30\n"})
    lab.remote.write({STEPS: b"a <- 12\nb <- 2\nc <- 30\n"}, "Someone else again")
    synced(lab)
    found = lab.client.get(f"/api/pipelines/edits/{edit['id']}").json()
    early = lab.client.post(
        f"/api/pipelines/edits/{edit['id']}/share",
        json={"confirmed": [], "version": found["updated_at"]},
    ).json()
    assert early["status"] == "conflict"  # found before anything was fetched or tested
    overlap = lab.client.post(
        f"/api/pipelines/edits/{edit['id']}/reapply", json={"version": early["updated_at"]}
    ).json()
    assert "<<<<<<< Your edit" in overlap["merged"][STEPS]
    assert overlap["edit"]["status"] == "conflict"  # unchanged until the person chooses
    written = lab.client.post(
        f"/api/pipelines/edits/{edit['id']}/reapply",
        json={"version": early["updated_at"], "resolutions": {STEPS: "a <- 13\nb <- 2\nc <- 30\n"}},
    ).json()
    assert written["edit"]["status"] == "draft" and not written["edit"]["upstream_changed"]
    saved = share(lab, written["edit"])
    assert saved["status"] == "saved" and lab.remote.show(STEPS) == "a <- 13\nb <- 2\nc <- 30"


def test_edit_before_accepting_turns_the_proposal_into_the_persons_edit(lab):
    synced(lab)
    cid = conversation(lab)
    proposal = turn(lab, cid, {STEPS: NEW_STEPS, "workflows/monthly.yaml": "name: monthly\n"})
    assert proposal is not None
    response = lab.client.post(f"/api/pipelines/proposals/{proposal.id}/edit")
    assert response.status_code == 200, response.text
    edit = response.json()
    assert edit["origin"] == {
        "proposal_id": proposal.id, "conversation_id": cid, "conversation_title": "Weekly steps",
    }  # fmt: skip
    assert edit["base"] == proposal.base
    assert {f["path"]: (f["text"], f["new"]) for f in edit["files"]} == {
        STEPS: (NEW_STEPS, False),
        "workflows/monthly.yaml": ("name: monthly\n", True),
    }
    # The proposal is replaced by it, and says so; it can't be accepted any more.
    replaced = lab.client.get(f"/api/pipelines/proposals/{proposal.id}").json()["proposal"]
    assert replaced["status"] == "superseded" and replaced["result"]["edit"] == edit["id"]
    again = lab.client.post(f"/api/pipelines/proposals/{proposal.id}/accept", json={})
    assert again.status_code == 409
    # The agent's next proposal holds only what it changes after this.
    assert turn(lab, cid, {}) is None
    # Each of its files is edited; one is left out; the rest shared, as the person.
    edit = keep(lab, edit, {STEPS: NEW_STEPS.replace("7", "14")})
    done = share(lab, edit)
    assert done["status"] == "saved", done
    message = git("log", "-1", "--format=%B", "main", cwd=lab.remote.bare)
    assert f"DataLab-Proposal: {proposal.id}" in message
    assert f"DataLab-Conversation: {cid}" in message and f"DataLab-Edit: {edit['id']}" in message
    assert "x * 14" in lab.remote.show(STEPS)


def test_a_file_already_being_edited_isnt_taken_by_another_edit(lab):
    synced(lab)
    start(lab)
    cid = conversation(lab)
    proposal = turn(lab, cid, {STEPS: NEW_STEPS})
    assert proposal is not None
    refused = lab.client.post(f"/api/pipelines/proposals/{proposal.id}/edit")
    assert refused.status_code == 409 and "already editing" in refused.json()["detail"]
    assert (
        lab.client.get(f"/api/pipelines/proposals/{proposal.id}").json()["proposal"]["status"]
        == "open"
    )


def test_discarding_shares_nothing_and_frees_the_file(lab):
    synced(lab)
    before = lab.remote.head()
    edit = keep(lab, start(lab), {STEPS: NEW_STEPS})
    gone = lab.client.post(f"/api/pipelines/edits/{edit['id']}/discard").json()
    assert gone["status"] == "discarded" and lab.remote.head() == before
    late = lab.client.post(
        f"/api/pipelines/edits/{edit['id']}/share", json={"version": gone["updated_at"]}
    )
    assert late.status_code == 409
    # Keeping, sharing and reapplying always say which version of the draft they're of.
    unversioned = lab.client.put(f"/api/pipelines/edits/{edit['id']}", json={"files": {}})
    assert unversioned.status_code == 422
    listed = lab.client.get("/api/pipelines/edits").json()
    assert [(e["id"], e["status"]) for e in listed] == [(edit["id"], "discarded")]
    assert start(lab)["id"] != edit["id"]


def test_a_save_cut_off_by_datalab_stopping_says_so(lab):
    synced(lab)
    edit = lab.pipelines.edits.get(start(lab)["id"])
    lab.pipelines.edits.store.update(edit, status="saving")
    assert lab.pipelines.edits.store.end_interrupted() == 1
    found = lab.pipelines.edits.get(edit.id)
    assert found.status == "failed" and "stopped while saving" in found.result["message"]


def test_practice_datalab_has_no_edits(tmp_path, github_keychain):
    settings = Settings(profile="practice", data_dir=tmp_path / "data", oracle=None)
    connection = db.connect(settings.database_file)
    store = ConversationStore(connection)
    manager = SessionManager(settings, store, SessionTokens())
    router = build_pipelines_router(
        PipelineServices(settings, connection, store, manager, auth=None, sandbox=FakeSandbox())
    )
    app = FastAPI()
    app.include_router(router)
    with TestClient(app) as client:
        status = client.get("/api/pipelines/status").json()
        assert (status["available"], status["practice"]) == (False, True)
        refused = client.post("/api/pipelines/edits", json={"path": STEPS})
        assert refused.status_code == 409 and "Practice" in refused.json()["detail"]
        assert client.get("/api/pipelines/edits").status_code == 409
    connection.close()


def test_git_never_drops_a_file_for_a_folder_of_the_same_name(lab):
    """The second guard, for every caller of commit_files (the knowledge base too)."""
    synced(lab)
    clone = lab.pipelines._repo().clone
    head = clone.remote_head()
    for files in (
        {"ihsDataR/DESCRIPTION/x.R": b"x\n"},  # in a "folder" that's a file
        {"ihsDataR/R": b"x\n"},  # a file where a folder is
        {"ihsDataR/new.R": b"x\n", "ihsDataR/new.R/y.R": b"y\n"},  # both at once
    ):
        with pytest.raises(GitError):
            clone.commit_files(head, files, "m", Identity("A", "a@example.org"))
    # Deleting the file first makes room for the folder.
    made = clone.commit_files(
        head,
        {"ihsDataR/DESCRIPTION": None, "ihsDataR/DESCRIPTION/x.R": b"x\n"},
        "m",
        Identity("A", "a@example.org"),
    )
    assert "ihsDataR/DESCRIPTION/x.R" in clone.ls_tree(made)


def test_names_too_long_for_some_computers_are_refused():
    assert name_problem("ihsDataR/R/" + "a" * 100 + ".R") is not None
    assert name_problem("/".join(["ihsDataR"] + ["folder"] * 30) + "/x.R") is not None
    assert name_problem("ihsDataR/tests/testthat/fixtures/weekly_steps_by_iso_week.csv") is None


def test_github_moving_on_elsewhere_is_rebased_and_pushed(lab):
    synced(lab)
    edit = keep(lab, start(lab), {STEPS: NEW_STEPS})
    lab.remote.write({"ihsDataR/R/dates.R": b"to_date <- function(x) x\n"}, "Someone else")
    done = share(lab, edit)
    assert done["status"] == "saved", done
    assert lab.remote.show("ihsDataR/R/dates.R") == "to_date <- function(x) x"
    assert lab.remote.show(STEPS) == NEW_STEPS.rstrip("\n")


def test_a_rejected_push_goes_round_again_strictly(lab, monkeypatch):
    """main moved on between the fetch and the push, on the edit's own file: the
    next round sees it and stops, rather than rebase over it."""
    synced(lab)
    edit = keep(lab, start(lab), {STEPS: NEW_STEPS})
    clone = lab.pipelines._repo().clone
    real = clone.push
    pushes = []

    def push(commit):
        if not pushes:
            lab.remote.write({STEPS: b"weekly_steps <- function(x) x + 1\n"}, "Someone else")
        pushes.append(commit)
        return real(commit)

    monkeypatch.setattr(clone, "push", push)
    done = share(lab, edit)
    assert len(pushes) == 1  # rejected, then the strict check stopped the second round
    assert done["status"] == "conflict" and done["result"]["conflicts"] == [STEPS]
    assert lab.remote.show(STEPS) == "weekly_steps <- function(x) x + 1"


def test_a_case_twin_saved_meanwhile_is_a_conflict(lab):
    synced(lab)
    edit = keep(lab, start(lab, "ihsDataR/R/new.R", new=True), {"ihsDataR/R/new.R": "a <- 1\n"})
    before = lab.remote.write({"ihsDataR/R/New.R": b"b <- 2\n"}, "Someone else")
    done = share(lab, edit)
    assert done["status"] == "conflict" and lab.remote.head() == before


def test_already_on_github_as_it_is_here_is_saved_not_a_conflict(lab):
    """Pushed from here just before DataLab stopped, say: not someone else's change."""
    synced(lab)
    edit = keep(lab, start(lab), {STEPS: NEW_STEPS})
    pushed = lab.remote.write({STEPS: NEW_STEPS.encode()}, "The same change")
    done = share(lab, edit)  # not synced: found on the fetch
    assert done["status"] == "saved" and "already on GitHub" in done["result"]["message"]
    assert lab.remote.head() == pushed
    synced(lab)
    other = keep(lab, start(lab), {STEPS: NEW_STEPS + "# more\n"})
    lab.remote.write({STEPS: (NEW_STEPS + "# more\n").encode()}, "Again")
    synced(lab)  # found before anything is fetched
    again = share(lab, other)
    assert again["status"] == "saved" and "already on GitHub" in again["result"]["message"]


def test_an_edit_whose_commit_the_clone_lost_is_made_again_from_its_text(lab):
    synced(lab)
    edit = keep(lab, start(lab), {STEPS: NEW_STEPS})
    found = lab.pipelines.edits.store.get(edit["id"])
    assert found is not None
    lab.pipelines.edits.store.update(found, commit="0" * 40, tree="0" * 40)
    shown = lab.client.get(f"/api/pipelines/edits/{edit['id']}").json()
    assert shown["files"][0]["text"] == NEW_STEPS
    repaired = lab.pipelines.edits.store.get(edit["id"])
    assert repaired is not None and repaired.commit != "0" * 40
    assert share(lab, shown)["status"] == "saved"


def test_a_missing_edit_is_404_and_other_errors_arent(lab, monkeypatch):
    synced(lab)
    assert lab.client.get("/api/pipelines/edits/pe_nope").status_code == 404
    edit = start(lab)

    def broken(*args, **kwargs):
        raise KeyError("a bug, not a missing edit")

    monkeypatch.setattr(lab.pipelines.edits, "check", broken)
    with pytest.raises(KeyError):
        lab.client.get(f"/api/pipelines/edits/{edit['id']}")


def test_a_generated_file_isnt_edited_by_hand_on_the_way_back(lab):
    lab.remote.write({"ihsDataR/man/weekly_steps.Rd": ROXYGEN_RD.encode()}, "Document")
    synced(lab)
    cid = conversation(lab)
    proposal = turn(lab, cid, {"ihsDataR/man/weekly_steps.Rd": None})
    assert proposal is not None
    edit = lab.client.post(f"/api/pipelines/proposals/{proposal.id}/edit").json()
    rd = "ihsDataR/man/weekly_steps.Rd"
    changed = lab.client.put(
        f"/api/pipelines/edits/{edit['id']}",
        json={"files": {rd: ROXYGEN_RD + "% by hand\n"}, "version": edit["updated_at"]},
    )
    assert changed.status_code == 409 and "roxygen2" in changed.json()["detail"]
    # Put back exactly as it was is fine.
    assert keep(lab, edit, {rd: ROXYGEN_RD})["files"][0]["text"] == ROXYGEN_RD
