// Typed calls to DataLab's API. Types come from the backend's OpenAPI schema
// (schema.d.ts, generated by `npm run api-types`).
//
// Each feature's calls live in their own file (conversations.ts, files.ts...);
// `api` gathers the Workspace's and Settings' calls so existing imports keep
// working. The newer tabs import theirs straight from their own file
// (`sqlApi` from "@/api/sql", and so on).
import { conversationsApi } from "./conversations";
import { exportsApi } from "./exports";
import { filesApi } from "./files";
import { healthApi } from "./health";
import { safetyApi } from "./safety";

export { ApiError, type FeatureStatus, SIGNED_OUT } from "./http";
export type { Health } from "./health";
export type { Conversation, Effort, Mode, Models, PlanSchema, QueryRecord } from "./conversations";
export type { Attachment, AttachResult, Checkpoint, FileRoot, RestoreResult, WorkspaceFile } from "./files";
export type { Destination, DestinationPlace, DestinationPlaces, ExportResult, FolderTest } from "./exports";
export type { CheckResult, SafetyReport } from "./safety";

export const api = {
  ...healthApi,
  ...conversationsApi,
  ...filesApi,
  ...exportsApi,
  ...safetyApi,
};
