// Typed calls to DataLab's API. Types come from the backend's OpenAPI schema
// (schema.d.ts, generated by `npm run api-types`).
import type { components } from "./schema";

type Schemas = components["schemas"];
export type Conversation = Schemas["ConversationOut"];
export type Mode = Schemas["ModeOut"];
export type QueryRecord = Schemas["QueryRecordOut"];
export type Effort = NonNullable<Schemas["NewMessage"]["effort"]>;
export type SafetyReport = Schemas["SafetyReportOut"];
export type CheckResult = Schemas["CheckResultOut"];

export interface Health {
  status: string;
  version: string;
  profile: "real" | "practice";
  database_configured: boolean;
  catalog_tables: number;
}

export class ApiError extends Error {
  constructor(
    readonly status: number,
    message: string,
  ) {
    super(message);
  }
}

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(path, {
    ...init,
    headers: { "content-type": "application/json", ...init?.headers },
  });
  if (!response.ok) {
    const body = await response.json().catch(() => ({}));
    const detail = typeof body.detail === "string" ? body.detail : response.statusText;
    throw new ApiError(response.status, detail);
  }
  return response.status === 204 ? (undefined as T) : response.json();
}

export const api = {
  health: () => request<Health>("/api/health"),
  modes: () => request<Mode[]>("/api/modes"),
  conversations: () => request<Conversation[]>("/api/conversations"),
  conversation: (id: string) => request<Conversation>(`/api/conversations/${id}`),
  createConversation: (mode: string, title: string) =>
    request<Conversation>("/api/conversations", {
      method: "POST",
      body: JSON.stringify({ mode, title }),
    }),
  deleteConversation: (id: string) =>
    request<void>(`/api/conversations/${id}`, { method: "DELETE" }),
  send: (id: string, text: string, effort?: Effort) =>
    request<Conversation>(`/api/conversations/${id}/messages`, {
      method: "POST",
      body: JSON.stringify({ text, effort }),
    }),
  stop: (id: string) => request<Conversation>(`/api/conversations/${id}/stop`, { method: "POST" }),
  dataAccessed: (id: string) => request<QueryRecord[]>(`/api/conversations/${id}/data-accessed`),
  lastSafetyReport: () => request<SafetyReport | null>("/api/safety/last"),
  runSafetyCheck: () => request<SafetyReport>("/api/safety/check", { method: "POST" }),
};
