/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/modes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Modes */
        get: operations["list_modes_api_modes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan-schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plan Schema
         * @description The kinds of analysis plan and their sections, for the plan card.
         */
        get: operations["get_plan_schema_api_plan_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description The approved models, for the picker. Asked of U-M GPT with DataLab's own key.
         */
        get: operations["list_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_api_conversations_get"];
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_api_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_api_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /** Delete Conversation */
        delete: operations["delete_conversation_api_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        /** Change Conversation */
        patch: operations["change_conversation_api_conversations__conversation_id__patch"];
        trace?: never;
    };
    "/api/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Message */
        post: operations["send_message_api_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop */
        post: operations["stop_api_conversations__conversation_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/continue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Continue Turn
         * @description Pick up the last turn where it left off, in the same thread (the chat
         *     offers it after a turn fails, say when the model service stayed busy).
         */
        post: operations["continue_turn_api_conversations__conversation_id__continue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rerun Review
         * @description Run the last turn's rigor review again, after it couldn't finish.
         */
        post: operations["rerun_review_api_conversations__conversation_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/approvals/{approval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer Approval
         * @description Approve (maybe edited) or decline a research-helper question.
         */
        post: operations["answer_approval_api_conversations__conversation_id__approvals__approval_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_conversations__conversation_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream
         * @description Server-sent events: everything after `after`, then live events.
         */
        get: operations["stream_api_conversations__conversation_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/data-accessed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Accessed */
        get: operations["data_accessed_api_conversations__conversation_id__data_accessed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Folder
         * @description Files as of the end of the last turn (or query results, as they are).
         */
        get: operations["list_folder_api_conversations__conversation_id__files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/files/{root}/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * File Content
         * @description A file's content for the in-app viewer: images, or the start of a text file.
         */
        get: operations["file_content_api_conversations__conversation_id__files__root___path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/previews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** New Preview */
        post: operations["new_preview_api_conversations__conversation_id__previews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/checkpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Checkpoints */
        get: operations["list_checkpoints_api_conversations__conversation_id__checkpoints_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/checkpoints/{number}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore */
        post: operations["restore_api_conversations__conversation_id__checkpoints__number__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/input-samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Samples
         * @description Synthetic files the practice profile can attach (empty elsewhere).
         */
        get: operations["samples_api_input_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/inputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Inputs */
        get: operations["list_inputs_api_conversations__conversation_id__inputs_get"];
        put?: never;
        /** Attach */
        post: operations["attach_api_conversations__conversation_id__inputs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/inputs/{attachment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Detach */
        delete: operations["detach_api_conversations__conversation_id__inputs__attachment_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export-destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Destinations */
        get: operations["list_destinations_api_export_destinations_get"];
        put?: never;
        /**
         * Add Destination
         * @description Choose a folder in the computer's picker and add it as a destination.
         */
        post: operations["add_destination_api_export_destinations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export-destinations/{destination_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Destination
         * @description Forget a destination. Files already exported there are untouched.
         */
        delete: operations["remove_destination_api_export_destinations__destination_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export */
        post: operations["export_api_conversations__conversation_id__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/safety/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Check */
        post: operations["run_check_api_safety_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/safety/last": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Last Check */
        get: operations["last_check_api_safety_last_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sql/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_sql_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sql/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check
         * @description The SQL check's verdict, for the editor. Nothing is run or logged.
         */
        post: operations["check_api_sql_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sql/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Run
         * @description Start a query. It runs in the background; follow it with GET /runs/{id}.
         */
        post: operations["start_run_api_sql_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sql/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description A run's state. With `wait`, answers when it finishes or after that many seconds.
         */
        get: operations["get_run_api_sql_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sql/runs/{run_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Run
         * @description Stop a query: it's cancelled in the database, and no result is kept.
         */
        post: operations["stop_run_api_sql_runs__run_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sql/results/{query_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Result
         * @description A page of a result. Only its first `preview_rows` rows can be shown;
         *     the whole result is in its file, and can be exported.
         */
        get: operations["result_api_sql_results__query_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sql/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History
         * @description This Playground's own queries, newest first.
         */
        get: operations["history_api_sql_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sql/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse
         * @description Every cohort's tables and columns, with their comments. Metadata only.
         */
        get: operations["browse_api_sql_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sql/catalog/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Tables whose names, columns or comments match, best first.
         */
        get: operations["search_api_sql_catalog_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sql/results/{query_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export
         * @description Export a result's file to an export folder, with a manifest saying what it is.
         */
        post: operations["export_api_sql_results__query_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_knowledge_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_workflows_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipelines/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_pipelines_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/provenance/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * File Provenance
         * @description How a workspace file (a path in /work, such as outputs/fig1.png) was made.
         */
        get: operations["file_provenance_api_conversations__conversation_id__provenance__path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_settings_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalAnswer */
        ApprovalAnswer: {
            /** Approve */
            approve: boolean;
            /**
             * Question
             * @default
             */
            question: string;
            /** Plan */
            plan?: {
                [key: string]: unknown;
            } | null;
            /** Change Type */
            change_type?: string | null;
        };
        /** AttachResult */
        AttachResult: {
            /** Added */
            added: components["schemas"]["AttachmentOut"][];
            /** Refused */
            refused: components["schemas"]["Refused"][];
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** AttachmentOut */
        AttachmentOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Container Path */
            container_path: string;
            /** Host Path */
            host_path: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "file" | "folder";
            /** Available */
            available: boolean;
        };
        /** CatalogCohort */
        CatalogCohort: {
            /** Schema Name */
            schema_name: string;
            /** Tables */
            tables: components["schemas"]["CatalogTable"][];
        };
        /** CatalogColumn */
        CatalogColumn: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Nullable */
            nullable: boolean;
            /** Comment */
            comment: string;
        };
        /** CatalogHit */
        CatalogHit: {
            /** Schema Name */
            schema_name: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Comment */
            comment: string;
            /** Matching Columns */
            matching_columns: string[];
        };
        /** CatalogTable */
        CatalogTable: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Comment */
            comment: string;
            /** Primary Key */
            primary_key: string[];
            /** Columns */
            columns: components["schemas"]["CatalogColumn"][];
        };
        /** ChainCommandOut */
        ChainCommandOut: {
            /** Id */
            id: string;
            /** Command */
            command: string;
            /** Exit Code */
            exit_code: number | null;
            /** Names File */
            names_file: boolean;
            /** Via Script */
            via_script: string | null;
            /** Seen In Output */
            seen_in_output: boolean;
        };
        /** ChainQueryOut */
        ChainQueryOut: {
            /** Id */
            id: string;
            /** Started At */
            started_at: string;
            /** Tables */
            tables: string[];
            /** Row Count */
            row_count: number | null;
            /** Result File */
            result_file: string | null;
            /** Read By */
            read_by: components["schemas"]["ChainReaderOut"][];
            /** In Turn */
            in_turn: boolean;
        };
        /** ChainReaderOut */
        ChainReaderOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "script" | "command";
            /** Ref */
            ref: string;
        };
        /** ChainScriptOut */
        ChainScriptOut: {
            /** Path */
            path: string;
            /** Sha256 */
            sha256: string;
            /** Names File */
            names_file: boolean;
        };
        /** CheckOut */
        CheckOut: {
            /** Ok */
            ok: boolean;
            /** Errors */
            errors: components["schemas"]["DiagnosticOut"][];
            /** Warnings */
            warnings: components["schemas"]["DiagnosticOut"][];
            /** Tables */
            tables: string[];
            /** Binds */
            binds: string[];
        };
        /** CheckResultOut */
        CheckResultOut: {
            /** Id */
            id: string;
            /** Promise */
            promise: string;
            /** Label */
            label: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pass" | "fail" | "skip";
            /** Detail */
            detail: string;
            /** Required */
            required: boolean;
        };
        /** CheckpointOut */
        CheckpointOut: {
            /** Number */
            number: number;
            /** Created At */
            created_at: string;
            /** Label */
            label: string;
            /** Turn */
            turn: number | null;
            /** Files */
            files: number;
            /** Bytes */
            bytes: number;
            /** Skipped */
            skipped: components["schemas"]["SkippedOut"][];
        };
        /** ColumnOut */
        ColumnOut: {
            /** Name */
            name: string;
            /** Type */
            type: string | null;
        };
        /** ConversationChange */
        ConversationChange: {
            /** Rigor Review */
            rigor_review?: boolean | null;
            /** Title */
            title?: string | null;
        };
        /** ConversationOut */
        ConversationOut: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "data" | "research";
            /** Mode */
            mode: string;
            /** Title */
            title: string;
            /** Model */
            model: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Rigor Review */
            rigor_review: boolean;
            /** Busy */
            busy: boolean;
        };
        /** DestinationOut */
        DestinationOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Available */
            available: boolean;
        };
        /** DiagnosticOut */
        DiagnosticOut: {
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning";
            position: components["schemas"]["PositionOut"] | null;
        };
        /** EventOut */
        EventOut: {
            /** Seq */
            seq: number;
            /** Created At */
            created_at: string;
            /** Type */
            type: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** ExportIn */
        ExportIn: {
            /** Destination Id */
            destination_id: string;
        };
        /** ExportOut */
        ExportOut: {
            /** Folder */
            folder: string;
            /** Files */
            files: string[];
        };
        /** FileOut */
        FileOut: {
            /** Path */
            path: string;
            /** Size */
            size: number;
            /** Modified */
            modified: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "html" | "image" | "csv" | "text" | "pdf" | "other";
            /** Checkpoint */
            checkpoint?: number | null;
        };
        /** FileProvenanceOut */
        FileProvenanceOut: {
            /** Path */
            path: string;
            /** Found */
            found: boolean;
            /** Summary */
            summary: string;
            /** Checkpoint */
            checkpoint?: number | null;
            /** Turn */
            turn?: number | null;
            /**
             * In Review
             * @default false
             */
            in_review: boolean;
            /**
             * Commands
             * @default []
             */
            commands: components["schemas"]["ChainCommandOut"][];
            /**
             * More Commands
             * @default 0
             */
            more_commands: number;
            /**
             * Edited Directly
             * @default false
             */
            edited_directly: boolean;
            /**
             * Scripts
             * @default []
             */
            scripts: components["schemas"]["ChainScriptOut"][];
            /**
             * Queries
             * @default []
             */
            queries: components["schemas"]["ChainQueryOut"][];
            /**
             * More Queries
             * @default 0
             */
            more_queries: number;
        };
        /** FileRef */
        FileRef: {
            /**
             * Root
             * @enum {string}
             */
            root: "outputs" | "work" | "results";
            /** Path */
            path: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryItem */
        HistoryItem: {
            /** Query Id */
            query_id: string;
            /** Status */
            status: string;
            /** Sql */
            sql: string;
            /** Binds */
            binds: {
                [key: string]: unknown;
            };
            /** Tables */
            tables: string[];
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Row Count */
            row_count: number | null;
            /** Elapsed Ms */
            elapsed_ms: number | null;
            /** Message */
            message: string | null;
            /** Has Result */
            has_result: boolean;
        };
        /** KnowledgeStatus */
        KnowledgeStatus: {
            /** Available */
            available: boolean;
            /**
             * Repo
             * @constant
             */
            repo: "not configured";
        };
        /** ModeOut */
        ModeOut: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "data" | "research";
            /** Description */
            description: string;
            /** Starters */
            starters: string[];
        };
        /** ModelsOut */
        ModelsOut: {
            /** Default */
            default: string;
            /** Available */
            available: string[];
        };
        /** NewConversation */
        NewConversation: {
            /**
             * Mode
             * @default analysis
             */
            mode: string;
            /**
             * Title
             * @default New conversation
             */
            title: string;
            /** Model */
            model?: string | null;
        };
        /** NewExport */
        NewExport: {
            /** Destination Id */
            destination_id: string;
            /** Files */
            files?: components["schemas"]["FileRef"][];
            report?: components["schemas"]["ReportIn"] | null;
            /** Checkpoint */
            checkpoint?: number | null;
            /**
             * Raw Html
             * @default false
             */
            raw_html: boolean;
        };
        /** NewInputs */
        NewInputs: {
            /**
             * Source
             * @enum {string}
             */
            source: "files" | "folder" | "sample";
            /** Sample */
            sample?: string | null;
        };
        /** NewMessage */
        NewMessage: {
            /** Text */
            text: string;
            /** Effort */
            effort?: ("low" | "medium" | "high" | "xhigh") | null;
        };
        /** NewPreview */
        NewPreview: {
            /**
             * Root
             * @enum {string}
             */
            root: "outputs" | "work" | "results";
            /** Path */
            path: string;
            /** Checkpoint */
            checkpoint?: number | null;
        };
        /** PipelinesStatus */
        PipelinesStatus: {
            /** Available */
            available: boolean;
        };
        /** PlanLimitsOut */
        PlanLimitsOut: {
            /** Section */
            section: number;
            /** Title */
            title: number;
            /** Rationale */
            rationale: number;
            /** Reason */
            reason: number;
            /** Additional */
            additional: number;
            /** Plan */
            plan: number;
        };
        /** PlanSchemaOut */
        PlanSchemaOut: {
            /** Schema Version */
            schema_version: number;
            /** Sections */
            sections: components["schemas"]["PlanSectionOut"][];
            /** Core */
            core: string[];
            /** Modules */
            modules: string[];
            /** Types */
            types: components["schemas"]["PlanTypeOut"][];
            limits: components["schemas"]["PlanLimitsOut"];
        };
        /** PlanSectionOut */
        PlanSectionOut: {
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Guidance */
            guidance: string;
        };
        /** PlanTypeOut */
        PlanTypeOut: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Summary */
            summary: string;
            /** Required */
            required: string[];
            /** Optional */
            optional: string[];
            /** Checks */
            checks: string;
        };
        /**
         * PositionOut
         * @description 1-based; the end is just after the last character.
         */
        PositionOut: {
            /** Line */
            line: number;
            /** Column */
            column: number;
            /** End Line */
            end_line: number;
            /** End Column */
            end_column: number;
        };
        /** PreviewOut */
        PreviewOut: {
            /** Url */
            url: string;
            /** Checkpoint */
            checkpoint: number;
        };
        /** QueryRecordOut */
        QueryRecordOut: {
            /** Id */
            id: string;
            /** Started At */
            started_at: string;
            /** Status */
            status: string;
            /** Sql Text */
            sql_text: string;
            /** Tables */
            tables: string[];
            /** Row Count */
            row_count: number | null;
            /** Elapsed Ms */
            elapsed_ms: number | null;
            /** Result File */
            result_file: string | null;
            /** Message */
            message: string | null;
        };
        /** Refused */
        Refused: {
            /** Path */
            path: string;
            /** Reason */
            reason: string;
        };
        /** ReportIn */
        ReportIn: {
            /** Html */
            html: string;
            /**
             * Css
             * @default
             */
            css: string;
        };
        /** RestoreOut */
        RestoreOut: {
            /** Written */
            written: number;
            /** Removed */
            removed: number;
            /** Left Alone */
            left_alone: string[];
            /** Not Restored */
            not_restored: string[];
        };
        /** ResultPageOut */
        ResultPageOut: {
            /** Query Id */
            query_id: string;
            /** Columns */
            columns: components["schemas"]["ColumnOut"][];
            /** Row Count */
            row_count: number | null;
            /** Offset */
            offset: number;
            /** Rows */
            rows: string[][];
            /** Preview Limit */
            preview_limit: number;
            /** Has More */
            has_more: boolean;
        };
        /** RunIn */
        RunIn: {
            /** Sql */
            sql: string;
            /** Binds */
            binds?: {
                [key: string]: string | number | null;
            };
        };
        /** RunOut */
        RunOut: {
            /** Id */
            id: string;
            /**
             * State
             * @enum {string}
             */
            state: "running" | "succeeded" | "failed" | "rejected" | "stopped";
            /** Sql */
            sql: string;
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Message */
            message: string | null;
            diagnostic: components["schemas"]["DiagnosticOut"] | null;
            /** Query Id */
            query_id: string | null;
            /** Row Count */
            row_count: number | null;
            /** Bytes Written */
            bytes_written: number | null;
            /** Elapsed Seconds */
            elapsed_seconds: number | null;
            /** Columns */
            columns: components["schemas"]["ColumnOut"][];
            /** Tables */
            tables: string[];
            /** Warnings */
            warnings: string[];
        };
        /** SafetyReportOut */
        SafetyReportOut: {
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at: string;
            /** Passed */
            passed: boolean;
            /** Passed Strict */
            passed_strict: boolean;
            /** Results */
            results: components["schemas"]["CheckResultOut"][];
        };
        /** SettingsStatus */
        SettingsStatus: {
            /** Available */
            available: boolean;
        };
        /** SkippedOut */
        SkippedOut: {
            /** Path */
            path: string;
            /** Reason */
            reason: string;
            /** Size */
            size: number | null;
        };
        /** SqlIn */
        SqlIn: {
            /** Sql */
            sql: string;
        };
        /** SqlStatus */
        SqlStatus: {
            /** Available */
            available: boolean;
            /** Database Configured */
            database_configured: boolean;
            /** Playground Id */
            playground_id: string;
            /** Preview Rows */
            preview_rows: number;
            /** Max Rows */
            max_rows: number;
            /** Max Bytes */
            max_bytes: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkflowsStatus */
        WorkflowsStatus: {
            /** Available */
            available: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_modes_api_modes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModeOut"][];
                };
            };
        };
    };
    get_plan_schema_api_plan_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanSchemaOut"];
                };
            };
        };
    };
    list_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsOut"];
                };
            };
        };
    };
    list_conversations_api_conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationOut"][];
                };
            };
        };
    };
    create_conversation_api_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewConversation"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_conversation_api_conversations__conversation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewMessage"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_api_conversations__conversation_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    continue_turn_api_conversations__conversation_id__continue_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rerun_review_api_conversations__conversation_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_approval_api_conversations__conversation_id__approvals__approval_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalAnswer"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_conversations__conversation_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_api_conversations__conversation_id__stream_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "last-event-id"?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_accessed_api_conversations__conversation_id__data_accessed_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryRecordOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_folder_api_conversations__conversation_id__files_get: {
        parameters: {
            query?: {
                root?: "outputs" | "work" | "results";
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    file_content_api_conversations__conversation_id__files__root___path__get: {
        parameters: {
            query?: {
                head?: number;
                checkpoint?: number | null;
            };
            header?: never;
            path: {
                conversation_id: string;
                root: "outputs" | "work" | "results";
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    new_preview_api_conversations__conversation_id__previews_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewPreview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_checkpoints_api_conversations__conversation_id__checkpoints_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckpointOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_api_conversations__conversation_id__checkpoints__number__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    samples_api_input_samples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    list_inputs_api_conversations__conversation_id__inputs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attach_api_conversations__conversation_id__inputs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewInputs"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detach_api_conversations__conversation_id__inputs__attachment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                attachment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_destinations_api_export_destinations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationOut"][];
                };
            };
        };
    };
    add_destination_api_export_destinations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DestinationOut"];
                };
            };
        };
    };
    remove_destination_api_export_destinations__destination_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                destination_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_conversations__conversation_id__exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewExport"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_check_api_safety_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyReportOut"];
                };
            };
        };
    };
    last_check_api_safety_last_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyReportOut"] | null;
                };
            };
        };
    };
    status_api_sql_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SqlStatus"];
                };
            };
        };
    };
    check_api_sql_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SqlIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_sql_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_sql_runs__run_id__get: {
        parameters: {
            query?: {
                wait?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_run_api_sql_runs__run_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    result_api_sql_results__query_id__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                query_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_sql_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    browse_api_sql_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogCohort"][];
                };
            };
        };
    };
    search_api_sql_catalog_search_get: {
        parameters: {
            query: {
                q: string;
                schemas?: string[] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_sql_results__query_id__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_knowledge_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeStatus"];
                };
            };
        };
    };
    status_api_workflows_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowsStatus"];
                };
            };
        };
    };
    status_api_pipelines_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelinesStatus"];
                };
            };
        };
    };
    file_provenance_api_conversations__conversation_id__provenance__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileProvenanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_settings_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsStatus"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
