"""The parity report as Markdown: verdicts first, then what differs, per column.

It holds only what compare.py returns: names, counts, value shapes, and
numeric means and sums. No rows or cells.
"""

from __future__ import annotations

from typing import Any

SIDES = {
    "live": "End to end: each side extracts from the synthetic database itself",
    "extracts": "Same extract: the prototype's steps run on v1's extracted CSVs",
}


def _status(entry: dict[str, Any]) -> str:
    return str(entry.get("status", "?"))


def _fmt(value: Any) -> str:
    if isinstance(value, float):
        return f"{value:.6g}"
    return str(value)


def _shapes(summary: dict[str, Any]) -> str:
    shapes = ", ".join(f"`{k}` {v}" for k, v in summary.get("shapes", {}).items())
    extra = f"; missing {summary.get('missing', 0)}; distinct {summary.get('distinct', 0)}"
    numeric = summary.get("numeric")
    if numeric:
        extra += f"; mean {_fmt(numeric['mean'])}, sum {_fmt(numeric['sum'])}"
    return (shapes or "none") + extra


def write_report(meta: dict[str, Any], results: dict[str, list[dict[str, Any]]]) -> str:
    lines = [
        "<!-- Generated by scripts/parity/parity.py. -->",
        "",
        f"- Generated: {meta['generated_at']}",
        f"- DataLab commit: `{meta['datalab_commit'][:12]}`"
        + (" (with uncommitted backend changes)" if meta.get("datalab_dirty") else ""),
        f"- ihs-pipelines commit: `{meta['pipelines_commit'][:12]}`",
        f"- Prototype commit: `{meta['prototype_commit'][:12]}`, "
        f"R image `{meta['prototype_image']}`",
        "",
    ]
    for side, entries in results.items():
        lines += [
            f"## {SIDES[side]}",
            "",
            "| Workflow | Prototype | v1 | File | Verdict |",
            "|---|---|---|---|---|",
        ]
        for entry in entries:
            files = entry["files"] or [{"name": "(no files)", "verdict": "missing"}]
            for index, file in enumerate(files):
                head = (
                    f"`{entry['name']}` | {_status(entry['prototype_status'])} | "
                    f"{_status(entry['v1_status'])}"
                    if index == 0
                    else " | | "
                )
                lines.append(f"| {head} | `{file['name']}` | {file['verdict']} |")
        lines.append("")
        for entry in entries:
            lines += _details(entry)
    return "\n".join(lines).rstrip() + "\n"


def _details(entry: dict[str, Any]) -> list[str]:
    out: list[str] = []
    for status in (entry["prototype_status"], entry["v1_status"]):
        if status.get("status") not in {"succeeded", None} and status.get("error"):
            out.append(f"- {status.get('side', '?')} {status['status']}: {status['error']}")
        for step in status.get("steps", []):
            if step.get("state") not in {"succeeded", "skipped"}:
                message = f": {step['message']}" if step.get("message") else ""
                out.append(f"- {status.get('side')} step `{step['id']}` {step['state']}{message}")
    for file in entry["files"]:
        if file["verdict"] == "identical":
            continue
        out.append(f"- `{file['name']}`: **{file['verdict']}**")
        rows, cols = file.get("rows"), file.get("columns")
        if rows:
            out.append(
                f"  - rows {rows['prototype']} / {rows['v1']}, columns {cols['prototype']} / "
                f"{cols['v1']} (prototype / v1)"
            )
        for note in file.get("notes", []):
            out.append(f"  - {note}")
        for key in ("only_in_prototype", "only_in_v1"):
            if file.get(key):
                out.append(
                    f"  - {key.replace('_', ' ')}: " + ", ".join(f"`{c}`" for c in file[key])
                )
        if "alignment" in file:
            a = file["alignment"]
            out.append(
                f"  - rows aligned by {a['by']} ({a['key_columns']} matching columns"
                f"{', unique' if a['unique'] else ', not unique'})"
            )
        for column, info in (file.get("columns_differing") or {}).items():
            cells = ", ".join(f"{k} {v}" for k, v in info["cells"].items()) or "no cell differences"
            cause = f" ({info['cause']})" if info.get("cause") else ""
            out.append(f"  - `{column}`: {cells}{cause}")
            out.append(f"    - prototype: {_shapes(info['prototype'])}")
            out.append(f"    - v1: {_shapes(info['v1'])}")
        if file.get("prototype") is not None and file["name"] == "qc":
            out.append(f"  - prototype {file['prototype']}, v1 {file['v1']}")
    if out:
        return [f"### `{entry['name']}`", "", *out, ""]
    return []
