import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { MemoryRouter } from "react-router";
import { beforeEach, expect, it, vi } from "vitest";

import {
  type PipelineEdit,
  type PipelineFinding,
  type PipelineProposalDetail,
  pipelinesApi,
  type PipelinesStatus,
} from "@/api/pipelines";

import { CHECK_DELAY_MS, EditView, readUnsaved } from "./EditView";
import { PipelinesPage } from "./PipelinesPage";
import { ProposalView } from "./ProposalView";

vi.mock("@/api/pipelines", () => ({
  pipelinesApi: {
    status: vi.fn(), sync: vi.fn(), files: vi.fn(), file: vi.fn(), proposals: vi.fn(), proposal: vi.fn(),
    test: vi.fn(), accept: vi.fn(), reject: vi.fn(), testLog: vi.fn(), edits: vi.fn(), startEdit: vi.fn(),
    editProposal: vi.fn(), getEdit: vi.fn(), keepEdit: vi.fn(), checkEdit: vi.fn(), testEdit: vi.fn(),
    shareEdit: vi.fn(), reapplyEdit: vi.fn(), discardEdit: vi.fn(),
  },
})); // prettier-ignore
vi.mock("@/api/client", () => ({ api: { conversations: vi.fn(async () => []) } }));
vi.mock("@/components/chat/DockedChat", () => ({ DockedChat: () => <p>chat</p> }));
// The editors as plain fields: what they show, their language, and typing into them.
vi.mock("@/components/editor/CodeEditor", () => ({
  CodeEditor: ({
    label,
    value,
    onChange,
    readOnly,
    language,
    diagnostics,
  }: {
    label: string;
    value: string;
    onChange?: (v: string) => void;
    readOnly?: boolean;
    language?: string;
    diagnostics?: { line: number; message: string }[];
  }) => (
    <div>
      <textarea
        aria-label={label}
        data-language={language}
        value={value}
        readOnly={readOnly}
        onChange={(e) => onChange?.(e.target.value)}
      />
      {(diagnostics ?? []).map((d) => (
        <span key={d.line + d.message} data-testid="diagnostic">
          {d.line}: {d.message}
        </span>
      ))}
    </div>
  ),
}));
vi.mock("@/components/editor/DiffView", () => ({
  DiffView: ({ label, original, modified }: { label: string; original: string; modified: string }) => (
    <div aria-label={label}>
      <pre data-testid="diff-original">{original}</pre>
      <pre data-testid="diff-modified">{modified}</pre>
    </div>
  ),
}));

const STEPS = "ihsDataR/R/steps.R";
const R = "weekly_steps <- function(x) x\n";
const status: PipelinesStatus = {
  available: true, practice: false, repo: "in sync", name: "SripadaLab-UM/ihs-pipelines", signed_in: true,
  account: { login: "yfang", name: "Yu Fang" }, head: "abc1234def", last_sync: "2026-09-27T10:00:00+00:00",
  last_error: null, ahead: 0, behind: 0, message: null,
}; // prettier-ignore
const edit = (more: Partial<PipelineEdit> = {}): PipelineEdit => ({
  id: "pe_1", status: "draft", base: "abc1234def", head: "abc1234def", created_at: "2026-09-27T10:00:00+00:00",
  updated_at: "v1", origin: null, result: null, commit: null, decided_by: null, test: null, findings: [],
  upstream_changed: false,
  files: [{ path: STEPS, text: R, new: false, before: R, diff: "", upstream_changed: false, theirs: null, theirs_state: "text", source_note: null }],
  ...more,
}); // prettier-ignore
const hook: PipelineFinding = {
  id: "f1", path: STEPS, rule: "load_hook", severity: "code", line: 2, text: ".onLoad <- function(l, p) NULL",
  message: ".onLoad runs whenever the package is loaded, on everyone's computer.",
}; // prettier-ignore

let client: QueryClient;
function open(target: Parameters<typeof EditView>[0]["target"] = { path: STEPS }, more: Partial<Parameters<typeof EditView>[0]> = {}) {
  client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  const onClose = vi.fn();
  const view = render(
    <MemoryRouter>
      <QueryClientProvider client={client}>
        <EditView target={target} repo="SripadaLab-UM/ihs-pipelines" signedIn onClose={onClose} {...more} />
      </QueryClientProvider>
    </MemoryRouter>,
  );
  return { ...view, onClose };
}
const source = () => screen.getByLabelText(`${STEPS}: your edit`);
const type = async (text: string) =>
  fireEvent.change(await screen.findByLabelText(`${STEPS}: your edit`), { target: { value: text } });

beforeEach(() => {
  sessionStorage.clear();
  localStorage.clear();
  window.matchMedia = vi.fn(() => ({ matches: true })) as never;
  vi.mocked(pipelinesApi.status).mockReset().mockResolvedValue(status);
  vi.mocked(pipelinesApi.files).mockReset().mockResolvedValue({
    head: "abc1234def",
    files: [
      { path: STEPS, size: R.length },
      { path: "ihsDataR/man/weekly_steps.Rd", size: 40 },
    ],
    more_files: 0,
  });
  vi.mocked(pipelinesApi.file).mockReset().mockImplementation(async (path) => ({
    path, head: "abc1234def", size: 30, text: path === STEPS ? R : "% Generated by roxygen2\n", too_large: false,
    editable: path === STEPS, draft: null,
    source_note: path === STEPS ? null : "roxygen2 writes it from the #' comments above the function in ihsDataR/R/.",
  })); // prettier-ignore
  vi.mocked(pipelinesApi.proposals).mockReset().mockResolvedValue([]);
  vi.mocked(pipelinesApi.edits).mockReset().mockResolvedValue([]);
  vi.mocked(pipelinesApi.startEdit).mockReset().mockResolvedValue(edit());
  vi.mocked(pipelinesApi.getEdit).mockReset().mockResolvedValue(edit());
  vi.mocked(pipelinesApi.checkEdit).mockReset().mockResolvedValue({ findings: [] });
  vi.mocked(pipelinesApi.keepEdit).mockReset().mockImplementation(async (_id, files) =>
    edit({ updated_at: "v2", files: [{ ...edit().files[0], text: files[STEPS] ?? null }] }),
  );
  vi.mocked(pipelinesApi.testEdit).mockReset();
  vi.mocked(pipelinesApi.shareEdit).mockReset();
  vi.mocked(pipelinesApi.reapplyEdit).mockReset();
  vi.mocked(pipelinesApi.discardEdit).mockReset().mockResolvedValue(edit({ status: "discarded" }));
  vi.mocked(pipelinesApi.editProposal).mockReset();
});

it("opens a file in the editor from Edit manually, highlighted as its language", async () => {
  client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  render(
    <MemoryRouter>
      <QueryClientProvider client={client}>
        <PipelinesPage />
      </QueryClientProvider>
    </MemoryRouter>,
  );
  fireEvent.click(await screen.findByRole("button", { name: "steps.R" }));
  fireEvent.click(await screen.findByRole("button", { name: /Edit manually/ }));
  await waitFor(() => expect(pipelinesApi.startEdit).toHaveBeenCalledWith(STEPS, false));
  await screen.findByLabelText(`${STEPS}: your edit`);
  expect(await screen.findByRole("heading", { name: "Editing steps.R" })).toBeInTheDocument();
  expect(screen.getByText("Your edit")).toBeInTheDocument();
  expect(source()).toHaveValue(R);
  expect(source()).toHaveAttribute("data-language", "r");
  // Reopened after a reload, it's the same edit.
  expect(sessionStorage.getItem("datalab:pipelines:edit")).toContain("id:pe_1");
});

it("says why a generated file can't be edited, and where to change it", async () => {
  client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  render(
    <MemoryRouter>
      <QueryClientProvider client={client}>
        <PipelinesPage />
      </QueryClientProvider>
    </MemoryRouter>,
  );
  fireEvent.click(await screen.findByRole("button", { name: "man" }));
  fireEvent.click(await screen.findByRole("button", { name: "weekly_steps.Rd" }));
  expect(await screen.findByText(/Read-only here: roxygen2 writes it from the #' comments/)).toBeInTheDocument();
  expect(screen.queryByRole("button", { name: /Edit manually/ })).toBeNull();
});

it("in practice DataLab, Edit manually is there but off: it's on the real DataLab", async () => {
  vi.mocked(pipelinesApi.status).mockResolvedValue({
    ...status, available: false, practice: true, repo: "not configured", signed_in: false,
    message: "Practice DataLab doesn't use the lab's repositories.",
  }); // prettier-ignore
  client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  render(
    <MemoryRouter>
      <QueryClientProvider client={client}>
        <PipelinesPage />
      </QueryClientProvider>
    </MemoryRouter>,
  );
  const button = await screen.findByRole("button", { name: /Edit manually/ });
  expect(button).toBeDisabled();
  expect(button).toHaveAttribute("title", "Available on the real DataLab");
  expect(pipelinesApi.edits).not.toHaveBeenCalled();
});

it("keeps a draft on this computer, and what's typed but not kept survives a reload", async () => {
  const first = open();
  await type(R + "# more\n");
  expect(screen.getByText("changes not kept yet")).toBeInTheDocument();
  expect(readUnsaved("pe_1")).toEqual({ files: { [STEPS]: R + "# more\n" }, version: "v1" });
  first.unmount();
  open({ id: "pe_1" });
  expect(await screen.findByText(/Restored changes you hadn't kept yet/)).toBeInTheDocument();
  expect(source()).toHaveValue(R + "# more\n");
  fireEvent.click(screen.getByRole("button", { name: "Keep as a draft on this computer" }));
  await waitFor(() => expect(pipelinesApi.keepEdit).toHaveBeenCalledWith("pe_1", { [STEPS]: R + "# more\n" }, "v1"));
  expect(await screen.findByText("Kept on this computer (not shared).")).toBeInTheDocument();
  expect(readUnsaved("pe_1")).toBeNull();
});

it("checks the text as it's typed, as the proposal's check, and marks the lines", async () => {
  vi.mocked(pipelinesApi.checkEdit).mockImplementation(async (_id, _path, text) => ({
    findings: text.includes(".onLoad") ? [hook] : [],
  }));
  open();
  expect(await screen.findByText(/The check passes/)).toBeInTheDocument();
  await type(R + ".onLoad <- function(l, p) NULL\n");
  // Once the typing stops for a moment.
  await waitFor(
    () => expect(pipelinesApi.checkEdit).toHaveBeenLastCalledWith("pe_1", STEPS, R + ".onLoad <- function(l, p) NULL\n"),
    { timeout: CHECK_DELAY_MS * 4 },
  );
  expect(await screen.findByTestId("diagnostic")).toHaveTextContent("2: .onLoad runs whenever the package is loaded");
  expect(screen.getByText(/The check: 1 to confirm/)).toBeInTheDocument();
  // Save & share waits for the person to confirm it.
  const save = screen.getByRole("button", { name: "Save & share" });
  expect(save).toBeDisabled();
  fireEvent.click(screen.getByRole("checkbox", { name: /steps.R:2.*it should run there/ }));
  expect(save).toBeEnabled();
});

it("runs the tests on the kept draft, in the proposals' container", async () => {
  vi.mocked(pipelinesApi.startEdit).mockResolvedValue(edit({ findings: [hook] }));
  vi.mocked(pipelinesApi.checkEdit).mockResolvedValue({ findings: [hook] });
  vi.mocked(pipelinesApi.testEdit).mockResolvedValue(
    edit({ updated_at: "v2", test: { id: "pt_1", status: "running", started_at: "t", tests: 0, passed: 0, failed: 0, skipped: 0, errors: 0, warnings: 0, files: [], more_files: 0, failures: [] } }),
  );
  open();
  await type("weekly_steps <- function(x) x * 7\n");
  fireEvent.click(await screen.findByRole("button", { name: /Run the tests/ }));
  await waitFor(() => expect(pipelinesApi.testEdit).toHaveBeenCalledWith("pe_1"));
  expect(pipelinesApi.keepEdit).toHaveBeenCalledWith("pe_1", { [STEPS]: "weekly_steps <- function(x) x * 7\n" }, "v1");
  expect(await screen.findByText("The package's tests are running…")).toBeInTheDocument();
});

it("shares the draft as the person: kept first, then Save & share with the confirmed findings", async () => {
  vi.mocked(pipelinesApi.startEdit).mockResolvedValue(edit({ findings: [hook] }));
  vi.mocked(pipelinesApi.checkEdit).mockResolvedValue({ findings: [hook] });
  vi.mocked(pipelinesApi.shareEdit).mockResolvedValue(edit({ status: "saved", commit: "c0ffee1234567" }));
  open();
  await type("weekly_steps <- function(x) x * 7\n");
  await waitFor(() => expect(pipelinesApi.checkEdit).toHaveBeenLastCalledWith("pe_1", STEPS, "weekly_steps <- function(x) x * 7\n"));
  fireEvent.click(screen.getByRole("checkbox", { name: /it should run there/ }));
  const save = screen.getByRole("button", { name: "Save & share" });
  await waitFor(() => expect(save).toBeEnabled());
  fireEvent.click(save);
  await waitFor(() => expect(pipelinesApi.shareEdit).toHaveBeenCalledWith("pe_1", ["f1"], "v2"));
  expect(pipelinesApi.keepEdit).toHaveBeenCalled();
  const done = await screen.findByRole("status");
  expect(done).toHaveTextContent("Shared to GitHub · commit c0ffee1");
  expect(within(done).getByRole("link", { name: "c0ffee1" })).toHaveAttribute(
    "href",
    "https://github.com/SripadaLab-UM/ihs-pipelines/commit/c0ffee1234567",
  );
});

it("shows the three versions when GitHub changed the file, and reapplies the edit", async () => {
  const changed = edit({
    status: "conflict",
    upstream_changed: true,
    result: { state: "conflict", message: "Someone changed ihsDataR/R/steps.R on GitHub since you started.", findings: [], conflicts: [STEPS], after_rebase: false },
    files: [{ ...edit().files[0], text: "a <- 10\n", before: "a <- 1\n", upstream_changed: true, theirs: "a <- 12\n" }],
  }); // prettier-ignore
  vi.mocked(pipelinesApi.startEdit).mockResolvedValue(changed);
  vi.mocked(pipelinesApi.reapplyEdit)
    .mockResolvedValueOnce({ edit: changed, merged: { [STEPS]: "<<<<<<< Your edit\na <- 10\n=======\na <- 12\n>>>>>>> The version now on GitHub\n" } })
    .mockResolvedValueOnce({ edit: edit({ files: [{ ...edit().files[0], text: "a <- 13\n", before: "a <- 12\n" }] }), merged: {} });
  open();
  const box = await screen.findByRole("region", { name: "Changed on GitHub since you started" });
  expect(within(box).getByLabelText(`The version now on GitHub: ${STEPS}`)).toHaveValue("a <- 12\n");
  expect(within(box).getByLabelText(`Where you started: ${STEPS}`)).toHaveValue("a <- 1\n");
  expect(within(box).getByLabelText(`Your edit: ${STEPS}`)).toHaveValue("a <- 10\n");
  expect(screen.getByRole("button", { name: "Save & share" })).toBeDisabled();
  fireEvent.click(within(box).getByRole("button", { name: "Reapply my edit on the new version" }));
  const resolve = await within(box).findByLabelText(`The version to keep of ${STEPS}`);
  const use = within(box).getByRole("button", { name: "Use this text on the new version" });
  expect(use).toBeDisabled(); // the overlap markers are still there
  fireEvent.change(resolve, { target: { value: "a <- 13\n" } });
  fireEvent.click(use);
  await waitFor(() => expect(pipelinesApi.reapplyEdit).toHaveBeenLastCalledWith("pe_1", "v1", { [STEPS]: "a <- 13\n" }));
  await waitFor(() => expect(screen.queryByRole("region", { name: "Changed on GitHub since you started" })).toBeNull());
  expect(source()).toHaveValue("a <- 13\n");
});

it("edits an assistant's proposal before accepting it: it becomes the person's edit", async () => {
  const detail: PipelineProposalDetail = {
    proposal: {
      id: "pp_1", conversation_id: "c1", conversation_title: "Weekly steps", status: "open", created_at: "t", updated_at: "t",
      turn: 2, base: "abc1234def", files: [{ path: STEPS, change: "modified" }], refused: [], result: null, commit: null,
      decided_by: null, test: null,
    },
    files: [{ path: STEPS, change: "modified", before: R, after: "x\n", binary: false, diff: "" }],
    findings: [],
  }; // prettier-ignore
  vi.mocked(pipelinesApi.proposal).mockResolvedValue(detail);
  vi.mocked(pipelinesApi.editProposal).mockResolvedValue(
    edit({ id: "pe_9", origin: { proposal_id: "pp_1", conversation_id: "c1", conversation_title: "Weekly steps" } }),
  );
  const onEdit = vi.fn();
  client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  const proposalView = render(
    <QueryClientProvider client={client}>
      <ProposalView id="pp_1" onBack={vi.fn()} onEdit={onEdit} />
    </QueryClientProvider>,
  );
  expect(await screen.findByText("Suggested by the assistant")).toBeInTheDocument();
  fireEvent.click(screen.getByRole("button", { name: /Edit before accepting/ }));
  await waitFor(() => expect(onEdit).toHaveBeenCalledWith("pe_9"));
  expect(pipelinesApi.editProposal).toHaveBeenCalledWith("pp_1");
  proposalView.unmount();

  // Opened, the edit says where it came from, and links back to the suggestion.
  vi.mocked(pipelinesApi.getEdit).mockResolvedValue(
    edit({ id: "pe_9", origin: { proposal_id: "pp_1", conversation_id: "c1", conversation_title: "Weekly steps" } }),
  );
  const onOpenProposal = vi.fn();
  open({ id: "pe_9" }, { onOpenProposal });
  expect(await screen.findByText(/From a change suggested by the assistant/)).toBeInTheDocument();
  expect(screen.getByText(/Weekly steps/)).toBeInTheDocument();
  fireEvent.click(screen.getByRole("button", { name: "See what it suggested" }));
  expect(onOpenProposal).toHaveBeenCalledWith("pp_1");
});

it("lists the person's edits beside the assistant's proposals, each labelled", async () => {
  vi.mocked(pipelinesApi.edits).mockResolvedValue([
    { id: "pe_1", status: "draft", paths: [STEPS], created_at: "t", updated_at: "2026-09-27T10:00:00+00:00", from_proposal: null },
  ]);
  client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  render(
    <MemoryRouter>
      <QueryClientProvider client={client}>
        <PipelinesPage />
      </QueryClientProvider>
    </MemoryRouter>,
  );
  expect(await screen.findByText(/1 edit of yours, kept on this computer/)).toBeInTheDocument();
  fireEvent.click(await screen.findByRole("tab", { name: "Changes (1)" }));
  const item = screen.getByRole("button", { name: /draft · not shared/ });
  expect(within(item).getByText(/Your edit/)).toBeInTheDocument();
  fireEvent.click(item);
  await waitFor(() => expect(pipelinesApi.getEdit).toHaveBeenCalledWith("pe_1"));
});

it("makes a new file where the repo takes one", async () => {
  vi.mocked(pipelinesApi.startEdit).mockResolvedValue(
    edit({ files: [{ ...edit().files[0], path: "ihsDataR/R/new.R", text: "", before: null, new: true, theirs_state: "deleted" }] }),
  );
  client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  render(
    <MemoryRouter>
      <QueryClientProvider client={client}>
        <PipelinesPage />
      </QueryClientProvider>
    </MemoryRouter>,
  );
  fireEvent.click(await screen.findByRole("button", { name: /New file/ }));
  const name = screen.getByRole("textbox", { name: "New file" });
  expect(name).toHaveValue("ihsDataR/R/");
  fireEvent.change(name, { target: { value: "ihsDataR/R/new.R" } });
  fireEvent.click(screen.getByRole("button", { name: "Create" }));
  await waitFor(() => expect(pipelinesApi.startEdit).toHaveBeenCalledWith("ihsDataR/R/new.R", true));
  await screen.findByText("new file");
  expect(screen.getByRole("heading", { name: "New file new.R" })).toBeInTheDocument();
});
