"""A person's own changes to the pipelines repo: the Pipelines tab's Edit
manually, New file, and Edit before accepting on an assistant's proposal.

No agent is involved. A person's edit is a proposal like the agent's, and
goes through the same steps, only its files come from the person's editor:

- **What can be changed.** Exactly what an agent's proposal may change
  (`proposal_problem`): files in `ihsDataR/` and `workflows/`, never
  `.github/`, with names every disk takes, plain text under the size limit.
  Files roxygen2 writes (`ihsDataR/man/*.Rd`, `NAMESPACE`) aren't edited by
  hand: `source_note` says where they come from.
- **Where it starts.** GitHub's `main` as last synced (for Edit before
  accepting, the proposal's own base): the edit's base, its "where you
  started". One open edit of a file at a time: opening the file again finds it.
- **Keep as a draft.** The files are kept in DataLab's database, on this
  computer, until the person shares or discards them. Each time, DataLab
  makes a commit of the base with the person's files (never pushed): its
  tree is what the tests run on, as a proposal's.
- **The check and the tests** are the proposal's: check.py (with the
  workflow check on workflow files), and the package's tests in the
  no-network container (testing.py).
- **Save & share** is share.save_and_share, as for a proposal, committed as
  the signed-in person with a `DataLab-Edit` trailer, but strict: if a file
  of the edit changed on GitHub since it began, it stops with a conflict
  instead of merging. The person sees their edit, the version now on
  GitHub, and where they started, and chooses: reapply their edit on the
  new version (a three-way merge; overlapping lines they resolve
  themselves), or write the text to keep. Nothing is overwritten silently.
- **Edit before accepting.** An assistant's proposal becomes the person's
  edit: its files, as the agent left them, on the proposal's base. The
  proposal is marked superseded (it names the edit), and its conversation's
  base moves on, as when it's discarded, so the agent's next proposal holds
  only what it changes after this.
"""

from __future__ import annotations

import asyncio
import json
import logging
import re
import secrets
import sqlite3
import threading
from collections.abc import Mapping
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any, Literal

from datalab.knowledge import check as kb
from datalab.knowledge.edits import merge3
from datalab.pipelines import share
from datalab.pipelines.check import Finding, Report, check, is_workflow_file
from datalab.pipelines.proposals import MAX_FILE_BYTES, TestRun, proposal_problem
from datalab.repos.git import Identity, safe_path
from datalab.repos.github import SignInNeeded
from datalab.textcheck import lone_surrogate, size_text

log = logging.getLogger(__name__)

EditStatus = Literal[
    "draft", "saving", "saved", "conflict", "check_failed", "tests_failed", "failed", "discarded"
]  # fmt: skip
# A person may still act on these.
OPEN: tuple[EditStatus, ...] = ("draft", "conflict", "check_failed", "tests_failed", "failed")
_REFS = "refs/datalab/pipeline-edits"  # keeps each edit's commit while it's open
_DATALAB = Identity("DataLab", "datalab@localhost")
# A new file's kind, by its extension: the text files a pipelines repo holds.
NEW_FILE_TYPES = {
    "r", "rmd", "qmd", "md", "yaml", "yml", "sql", "py", "csv", "tsv", "json", "txt", "sh",
}  # fmt: skip
_ROXYGEN = re.compile(r"\A\s*[%#] Generated by roxygen2")
MAX_RECENT = 20  # finished edits listed beside the open ones


class EditRefused(RuntimeError):
    """The edit can't be made or changed now. The message is for the person."""


class EditConflict(EditRefused):
    """Another window changed the draft since this one read it."""


@dataclass
class EditFile:
    text: str | None  # None: the edit deletes it
    new: bool = False  # not in the edit's base

    def to_dict(self) -> dict[str, Any]:
        return {"text": self.text, "new": self.new}


@dataclass
class Edit:
    id: str
    base: str
    files: dict[str, EditFile]
    status: EditStatus
    commit: str  # the base with the files, never pushed
    tree: str
    created_at: str
    updated_at: str
    origin: dict[str, Any] = field(default_factory=dict)
    result: dict[str, Any] = field(default_factory=dict)
    saved_commit: str | None = None
    decided_by: str | None = None

    def contents(self) -> dict[str, bytes | None]:
        return {p: None if f.text is None else f.text.encode() for p, f in self.files.items()}


@dataclass(frozen=True)
class Upstream:
    """A file of the edit on GitHub's main as last synced, against the edit's base."""

    before: str | None  # at the base (None: not there)
    theirs: str | None  # now (None: not there, or not text)
    theirs_state: Literal["text", "deleted", "not text"]
    changed: bool


class EditStore:
    def __init__(self, db: sqlite3.Connection) -> None:
        self._db = db
        self._lock = threading.Lock()

    def add(self, edit: Edit) -> Edit:
        with self._lock:
            self._db.execute(
                "INSERT INTO pipeline_edits (id, base, files_json, status, origin_json, "
                "edit_commit, tree, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
                (
                    edit.id, edit.base, _files_json(edit.files), edit.status,
                    json.dumps(edit.origin), edit.commit, edit.tree, edit.created_at,
                    edit.updated_at,
                ),
            )  # fmt: skip
        return edit

    def get(self, edit_id: str) -> Edit | None:
        with self._lock:
            row = self._db.execute(
                "SELECT * FROM pipeline_edits WHERE id = ?", (edit_id,)
            ).fetchone()
        return _edit(row) if row else None

    def list_open(self) -> list[Edit]:
        marks = ", ".join("?" for _ in (*OPEN, "saving"))
        with self._lock:
            rows = self._db.execute(
                f"SELECT * FROM pipeline_edits WHERE status IN ({marks}) ORDER BY updated_at DESC",
                (*OPEN, "saving"),
            ).fetchall()
        return [_edit(r) for r in rows]

    def list_recent(self, limit: int = MAX_RECENT) -> list[Edit]:
        """The open edits, then the latest finished ones."""
        with self._lock:
            rows = self._db.execute(
                "SELECT * FROM pipeline_edits WHERE status IN ('saved', 'discarded') "
                "ORDER BY updated_at DESC LIMIT ?",
                (limit,),
            ).fetchall()
        return self.list_open() + [_edit(r) for r in rows]

    def open_for(self, path: str) -> Edit | None:
        return next((e for e in self.list_open() if path in e.files), None)

    def update(self, edit: Edit, **changes: Any) -> Edit:
        for key, value in changes.items():
            setattr(edit, key, value)
        edit.updated_at = _now()
        with self._lock:
            self._db.execute(
                "UPDATE pipeline_edits SET base = ?, files_json = ?, status = ?, edit_commit = ?, "
                "tree = ?, result_json = ?, commit_sha = ?, decided_by = ?, updated_at = ? "
                "WHERE id = ?",
                (
                    edit.base, _files_json(edit.files), edit.status, edit.commit, edit.tree,
                    json.dumps(edit.result), edit.saved_commit, edit.decided_by, edit.updated_at,
                    edit.id,
                ),
            )  # fmt: skip
        return edit

    def end_interrupted(self) -> int:
        """A save cut off by DataLab stopping didn't finish: say so."""
        result = {"state": "failed", "message": "DataLab stopped while saving. Try again."}
        with self._lock:
            done = self._db.execute(
                "UPDATE pipeline_edits SET status = 'failed', result_json = ?, updated_at = ? "
                "WHERE status = 'saving'",
                (json.dumps(result), _now()),
            )
        return done.rowcount


class PipelineEdits:
    """The Pipelines tab's own editing, on the Pipelines service's clone,
    sign-in, check and tests."""

    def __init__(self, pipelines: Any, database: sqlite3.Connection) -> None:
        # pipelines: service.Pipelines (not imported: it imports this module).
        self._pipelines = pipelines
        self.store = EditStore(database)
        self._lock = threading.Lock()
        if pipelines.available:
            self.store.end_interrupted()

    @property
    def _repo(self):
        return self._pipelines._repo()

    @property
    def clone(self):
        return self._repo.clone

    # Starting, reading ---------------------------------------------------------

    def start(self, path: str, *, new: bool = False) -> Edit:
        """The open edit of `path`, or a new one from the file as last synced.
        `new`: a file that isn't in the repo yet."""
        self._repo  # noqa: B018  # not available: say so first
        if problem := editable_problem(path):
            raise EditRefused(problem)
        with self._lock:
            found = self.store.open_for(path)
            if found is not None:
                return found
            with self.clone.lock:
                head = self.clone.remote_head()
                if head is None:
                    raise EditRefused("Sync the pipelines repo first (Pipelines tab, Sync).")
                entries = self.clone.ls_tree(head)
                entry = entries.get(path)
                content = (
                    self.clone.read_blobs([entry.blob]).get(entry.blob, b"")
                    if entry is not None and entry.regular
                    else None
                )
            if new:
                if content is not None or entry is not None:
                    raise EditRefused(f"There's already a file at {path}: open it and edit it.")
                if problem := new_file_problem(path, entries):
                    raise EditRefused(problem)
                text = ""
            else:
                if content is None:
                    raise EditRefused(f"There's no {path} in the pipelines repo as last synced.")
                if len(content) > MAX_FILE_BYTES:
                    raise EditRefused(
                        f"{path} is over the {size_text(MAX_FILE_BYTES)} limit for editing here."
                    )
                current = kb.as_text(content)
                if current is None:
                    raise EditRefused(f"{path} isn't a text file, so it can't be edited here.")
                if note := generated_note(path, current):
                    raise EditRefused(f"{path} can't be edited by hand. {note}")
                text = current
            return self._add(head, {path: EditFile(text, new=content is None)}, {})

    def from_proposal(self, proposal_id: str) -> Edit:
        """Edit before accepting: the proposal's files as the person's edit,
        on the proposal's base. The proposal is superseded by it."""
        pipelines = self._pipelines
        proposal = pipelines.get(proposal_id)
        with pipelines._lock(proposal.conversation_id), self._lock:
            proposal = pipelines._actionable(proposal_id)
            if proposal.status == "saving":
                raise EditRefused("This proposal is being saved.")
            if not proposal.files:
                raise EditRefused("There's nothing in this proposal to edit.")
            files: dict[str, EditFile] = {}
            for change in proposal.files:
                taken = self.store.open_for(change.path)
                if taken is not None:
                    raise EditRefused(
                        f"You're already editing {change.path} on this computer. Share or "
                        "discard that edit first (Pipelines tab, Changes)."
                    )
                raw = pipelines._agent_bytes(proposal.conversation_id, change)
                text = kb.as_text(raw) if raw is not None else None
                if raw is not None and text is None:
                    raise EditRefused(
                        f"{change.path} isn't a text file, so it can't be edited here."
                    )
                files[change.path] = EditFile(text, new=change.change == "added")
            origin = {"proposal_id": proposal.id, "conversation_id": proposal.conversation_id}
            edit = self._add(proposal.base, files, origin)
            pipelines.store.set_base(proposal.conversation_id, proposal.commit)
            pipelines.store.update(
                proposal,
                status="superseded",
                result={
                    "state": "superseded",
                    "message": "Replaced by your edit of it: it's shared from there.",
                    "edit": edit.id,
                },
            )
            return edit

    def get(self, edit_id: str) -> Edit:
        edit = self.store.get(edit_id)
        if edit is None:
            raise LookupError("No such edit.")
        return edit

    def upstream(self, edit: Edit) -> dict[str, Upstream]:
        """Each file of the edit at its base and on GitHub's main as last synced."""
        with self.clone.lock:
            head = self.clone.remote_head()
            then = self.clone.ls_tree(edit.base, *edit.files)
            now = self.clone.ls_tree(head, *edit.files) if head else {}
            blobs = self.clone.read_blobs(
                e.blob for e in [*then.values(), *now.values()] if e.regular
            )
        found = {}
        for path in edit.files:
            a, b = then.get(path), now.get(path)
            before = kb.as_text(blobs.get(a.blob, b"")) if a is not None else None
            raw = blobs.get(b.blob) if b is not None else None
            theirs = kb.as_text(raw) if raw is not None else None
            state = "deleted" if raw is None else "text" if theirs is not None else "not text"
            changed = (a.blob if a else None) != (b.blob if b else None)
            found[path] = Upstream(before, theirs, state, changed)
        return found

    def head(self) -> str | None:
        with self.clone.lock:
            return self.clone.remote_head()

    def check(self, edit: Edit, path: str | None = None, text: str | None = None) -> Report:
        """The check, as Save & share runs it first: on the kept files, or with
        `path` as `text` (what's in the editor now)."""
        files = edit.contents()
        extra: list[Finding] = []
        if path is not None:
            if path not in edit.files:
                raise EditRefused(f"{path} isn't in this edit.")
            if text is not None and (problem := text_problem(path, text)):
                extra.append(Finding(path, "not_text", "error", problem))
            else:
                files[path] = None if text is None else text.encode()
        report = check(files, self._pipelines.workflow_check(edit.commit, overlay=files))
        report.findings = extra + report.findings
        return report

    def latest_test(self, edit: Edit) -> TestRun | None:
        return self._pipelines.store.latest_test(edit.tree)

    # Changing --------------------------------------------------------------------

    def keep(self, edit_id: str, files: Mapping[str, str | None], version: str | None) -> Edit:
        """Keep as a draft on this computer. Never GitHub. `files` is the edit's
        files as the person has them (a file left out is left out of the edit)."""
        with self._lock:
            edit = self._open(edit_id, version)
            if not files:
                raise EditRefused("An edit needs at least one file: discard it instead.")
            kept: dict[str, EditFile] = {}
            for path, text in files.items():
                had = edit.files.get(path)
                if had is None:
                    raise EditRefused(f"{path} isn't in this edit: open it with Edit manually.")
                if text is not None and (problem := text_problem(path, text)):
                    raise EditRefused(problem)
                changed = text != had.text and had.text is not None
                if changed and (note := generated_note(path, had.text or "")):
                    raise EditRefused(f"{path} can't be edited by hand. {note}")
                if text is None and had.text is not None and had.new:
                    raise EditRefused(f"{path} is new in this edit: leave it out instead.")
                kept[path] = EditFile(text, had.new)
            commit, tree = self._commit(edit.id, edit.base, kept)
            return self.store.update(
                edit, files=kept, commit=commit, tree=tree, status="draft", result={}
            )

    def discard(self, edit_id: str) -> Edit:
        with self._lock:
            edit = self._open(edit_id, None)
            self._forget_ref(edit.id)
            return self.store.update(
                edit,
                status="discarded",
                result={"state": "discarded", "message": "Discarded. Nothing was shared."},
            )

    def reapply(
        self, edit_id: str, version: str | None, resolutions: Mapping[str, str] | None = None
    ) -> tuple[Edit, dict[str, str]]:
        """Move the edit onto the files as on GitHub now. A file in
        `resolutions` takes that text; any other file that changed there has
        the person's changes merged in (a three-way merge). Returns the edit,
        and the files that didn't merge cleanly, with the overlapping lines
        marked (the edit is then unchanged)."""
        resolutions = resolutions or {}
        with self._lock:
            edit = self._open(edit_id, version)
            head = self.head()
            if head is None:
                raise EditRefused("Sync the pipelines repo first.")
            upstream = self.upstream(edit)
            moved = {p: u for p, u in upstream.items() if u.changed}
            if not moved:
                return edit, {}
            files = dict(edit.files)
            unresolved: dict[str, str] = {}
            for path, up in moved.items():
                ours = edit.files[path].text
                if path in resolutions:
                    text = resolutions[path]
                    if problem := text_problem(path, text):
                        raise EditRefused(problem)
                    files[path] = EditFile(text, up.theirs_state == "deleted")
                    continue
                if up.theirs_state == "not text":
                    raise EditRefused(f"{path} isn't text on GitHub any more.")
                if ours is None:
                    if up.theirs_state == "deleted":
                        del files[path]  # deleted there too: nothing left to change
                        continue
                    raise EditRefused(
                        f"You're deleting {path}, and someone changed it on GitHub since. Leave "
                        "it out of your edit, or discard the edit and start again."
                    )
                if up.theirs_state == "deleted":
                    unresolved[path] = ours  # to keep, or not, as a new file
                    continue
                merged, clean = merge3(self.clone, ours, up.before or "", up.theirs or "")
                if clean:
                    files[path] = EditFile(merged, False)
                else:
                    unresolved[path] = merged
            if unresolved:
                return edit, unresolved
            if not files:
                raise EditRefused("Nothing of this edit is left to share: discard it.")
            commit, tree = self._commit(edit.id, head, files)
            edit = self.store.update(
                edit, base=head, files=files, commit=commit, tree=tree, status="draft", result={}
            )
            return edit, {}

    # Tests, Save & share -------------------------------------------------------

    async def start_tests(self, edit_id: str) -> TestRun:
        edit = await asyncio.to_thread(self._open, edit_id, None)
        return await self._pipelines.start_tests_on(edit.commit, edit.tree)

    async def share(self, edit_id: str, confirmed: list[str], version: str | None) -> Edit:
        """Start Save & share as the signed-in person, in the background; the
        edit, now saving (or in conflict, if GitHub's file moved on)."""
        repo = self._repo
        account = await asyncio.to_thread(repo.auth.account)
        if account is None:
            raise SignInNeeded("Sign in to GitHub to share changes.")

        def begin() -> tuple[Edit, bool]:
            with self._lock:
                edit = self._open(edit_id, version)
                upstream = self.upstream(edit)
                if all(
                    u.before == edit.files[p].text and not edit.files[p].new
                    for p, u in upstream.items()
                ):
                    raise EditRefused("There's no change to share yet.")
                moved = sorted(p for p, u in upstream.items() if u.changed)
                if moved:
                    return self.store.update(
                        edit,
                        status="conflict",
                        result=_conflict(moved, self.head()),
                        decided_by=account.login,
                    ), False
                return self.store.update(edit, status="saving", result={}), True

        edit, go = await asyncio.to_thread(begin)
        if not go:
            return edit
        origin = edit.origin
        trailers = [("DataLab-Edit", edit.id)]
        if origin.get("proposal_id"):
            trailers = [
                ("DataLab-Conversation", str(origin.get("conversation_id") or "")),
                ("DataLab-Proposal", str(origin["proposal_id"])),
                *trailers,
            ]
        request = share.Share(
            base=edit.base,
            commit=edit.commit,
            tree=edit.tree,
            files=edit.contents(),
            author=Identity(account.display_name, account.email),
            login=account.login,
            confirmed=confirmed,
            trailers=tuple(trailers),
            workflows=self._pipelines.workflow_check,
            by_person=True,
            strict=True,
        )
        self._pipelines._track_save(edit.id, self._save(edit, request))
        return edit

    async def _save(self, edit: Edit, request: share.Share) -> None:
        pipelines = self._pipelines
        try:
            result = await share.save_and_share(
                self.clone, request, lambda commit, tree: pipelines._tested(commit, tree)
            )
        except asyncio.CancelledError:
            await asyncio.to_thread(
                self.store.update,
                edit,
                status="failed",
                result={"state": "failed", "message": "Saving was stopped. Try again."},
            )
            raise
        except Exception as error:
            log.exception("Save & share failed for %s", edit.id)
            result = share.SaveResult("failed", f"Saving failed ({type(error).__name__}).")
        status: EditStatus = {
            "saved": "saved",
            "nothing to save": "saved",
            "conflict": "conflict",
            "check_failed": "check_failed",
            "tests_failed": "tests_failed",
            "failed": "failed",
        }[result.state]  # type: ignore[assignment]

        def finish() -> None:
            outcome = result.to_dict()
            if status == "conflict":
                outcome = {**outcome, **_conflict(result.conflicts, result.upstream)}
            if status == "saved":
                self._repo.saved(result.commit)
                self._forget_ref(edit.id)
            self.store.update(
                edit,
                status=status,
                result=outcome,
                saved_commit=result.commit if status == "saved" else None,
                decided_by=request.login,
            )

        await asyncio.to_thread(finish)

    # Inside ----------------------------------------------------------------------

    def _add(self, base: str, files: dict[str, EditFile], origin: dict[str, Any]) -> Edit:
        edit_id = f"pe_{secrets.token_hex(8)}"
        commit, tree = self._commit(edit_id, base, files)
        now = _now()
        return self.store.add(
            Edit(edit_id, base, files, "draft", commit, tree, now, now, origin=origin)
        )

    def _commit(self, edit_id: str, base: str, files: Mapping[str, EditFile]) -> tuple[str, str]:
        """The base with the person's files: a commit never pushed, kept by a ref."""
        contents = {p: None if f.text is None else f.text.encode() for p, f in files.items()}
        with self.clone.lock:
            commit = self.clone.commit_files(
                base,
                contents,
                f"{edit_id}: a person's edit in DataLab\n\nNever pushed.\n",
                _DATALAB,
            )
            tree = self.clone.text("rev-parse", f"{commit}^{{tree}}")
            self.clone.set_ref(f"{_REFS}/{edit_id}", commit)
        return commit, tree

    def _forget_ref(self, edit_id: str) -> None:
        with self.clone.lock:
            self.clone.git("update-ref", "-d", f"{_REFS}/{edit_id}", check=False)

    def _open(self, edit_id: str, version: str | None) -> Edit:
        edit = self.get(edit_id)
        if edit.status not in OPEN:
            raise EditRefused(f"This edit is {edit.status.replace('_', ' ')}.")
        if version is not None and version != edit.updated_at:
            raise EditConflict(
                "This draft was changed in another window since you opened it. Nothing was "
                "saved: reload it to see that version."
            )
        return edit


# Rules --------------------------------------------------------------------------


def editable_problem(path: str) -> str | None:
    """Why a person can't change `path` in DataLab, or None."""
    if lone_surrogate(path) is not None or not safe_path(path):
        return "That name can't be used in the pipelines repo."
    if problem := proposal_problem(path):
        return f"{path} can't be changed here: {problem}."
    return None


def source_note(path: str, text: str | None) -> str | None:
    """Why a file of the repo is read-only here, and how to change it, or None."""
    if path.startswith(".github/"):
        return (
            "It's the repo's automation (.github/): DataLab's GitHub sign-in may change the "
            "repo's contents only. Change it on GitHub, or ask the DataLab maintainer."
        )
    if not path.startswith(("ihsDataR/", "workflows/")):
        return (
            "Only ihsDataR/ (the package) and workflows/ (the workflow files) are changed in "
            "DataLab; the rest of the repo is there to read. Change it on GitHub."
        )
    if text is not None and (note := generated_note(path, text)):
        return note
    if editable_problem(path):
        return "Its name isn't one every computer takes, so it isn't changed in DataLab."
    return None


def generated_note(path: str, text: str) -> str | None:
    """Files roxygen2 writes from the package's R code: where to change them instead."""
    if not path.startswith("ihsDataR/") or not _ROXYGEN.match(text):
        return None
    if path == "ihsDataR/NAMESPACE":
        return (
            "roxygen2 writes it from the @export and @import tags in ihsDataR/R/. Change "
            "those tags, then ask the Pipelines assistant to run devtools::document()."
        )
    return (
        "roxygen2 writes it from the #' comments above the function in ihsDataR/R/. Edit "
        "those comments, then ask the Pipelines assistant to run devtools::document()."
    )


def new_file_problem(path: str, entries: Mapping[str, Any]) -> str | None:
    """Why a new file can't be made at `path` (as well as `editable_problem`)."""
    name = path.rsplit("/", 1)[-1]
    extension = name.rsplit(".", 1)[-1].lower() if "." in name else ""
    if path.endswith("/") or not name:
        return "Give the new file a name."
    if path.startswith("workflows/") and not is_workflow_file(path):
        return "A new workflow file is workflows/<name>.yaml."
    if extension not in NEW_FILE_TYPES:
        kinds = ", ".join(f".{k}" for k in sorted(NEW_FILE_TYPES))
        return f"A new file here is a text file: {kinds}."
    lowered = path.lower()
    clash = next((p for p in entries if p.lower() == lowered), None)
    if clash is not None:
        return f"There's already {clash} (names differing only in case clash on Windows and Mac)."
    if any(p.startswith(path + "/") for p in entries):
        return f"{path} is a folder in the repo."
    return None


def text_problem(path: str, text: str) -> str | None:
    if (not_text := lone_surrogate(text)) is not None:
        return f"Line {not_text.line}: {not_text.message}"
    if "\0" in text:
        return f"{path} must be plain text."
    if len(text.encode()) > MAX_FILE_BYTES:
        return f"{path} must be under {size_text(MAX_FILE_BYTES)}."
    return None


def _conflict(paths: list[str], upstream: str | None) -> dict[str, Any]:
    names = ", ".join(paths)
    return {
        "state": "conflict",
        "message": (
            f"Someone changed {names} on GitHub since you started. Nothing was shared: see the "
            "versions, and choose what to keep."
        ),
        "conflicts": paths,
        "upstream": upstream,
    }


def _files_json(files: Mapping[str, EditFile]) -> str:
    return json.dumps({p: f.to_dict() for p, f in files.items()})


def _edit(row: sqlite3.Row) -> Edit:
    return Edit(
        id=row["id"],
        base=row["base"],
        files={
            p: EditFile(f.get("text"), bool(f.get("new")))
            for p, f in json.loads(row["files_json"]).items()
        },
        status=row["status"],
        commit=row["edit_commit"],
        tree=row["tree"],
        created_at=row["created_at"],
        updated_at=row["updated_at"],
        origin=json.loads(row["origin_json"]),
        result=json.loads(row["result_json"]),
        saved_commit=row["commit_sha"],
        decided_by=row["decided_by"],
    )


def _now() -> str:
    return datetime.now(UTC).isoformat(timespec="microseconds")
