"""The Codex `config.toml` each session runs with.

Verified with Codex 0.157.1 in the spike (spikes/2026-09-26-codex-gateway).
Most features that open new channels are on by default, so every one is
switched off explicitly. The session token is the only credential; it works
only through the gateway, and only for this session.
"""

from __future__ import annotations

import json

from datalab.sessions.tokens import SessionKind

CODEX_VERSION = "0.157.1"
TOKEN_ENV = "DATALAB_SESSION_TOKEN"

# Codex features that are off in every session.
_FEATURES_OFF = (
    "memories",
    "apps",
    "plugins",
    "remote_plugin",
    "browser_use",
    "browser_use_external",
    "in_app_browser",
    "computer_use",
    "image_generation",
    "multi_agent",
    "realtime_conversation",
    "tool_suggest",
    "skill_mcp_dependency_install",
    "workspace_dependencies",
    "daemon_auto_start",
    "goals",
    "auth_elicitation",
)


def render(kind: SessionKind, *, model: str, tool_timeout_seconds: int) -> str:
    """Return the config.toml text for a session of this kind."""
    web_search = "live" if kind == "research" else "disabled"
    lines = [
        "# Generated by DataLab for one session. Do not edit.",
        f"model = {json.dumps(model)}",  # a JSON string is a valid TOML string
        'model_provider = "datalab"',
        # The container is the sandbox; Codex's own Linux sandbox needs
        # privileges the container doesn't have.
        'sandbox_mode = "danger-full-access"',
        # Commands never prompt; DataLab's own approval requests (MCP
        # elicitations) reach the user. "never" would silently decline them.
        "approval_policy = { granular = { sandbox_approval = false, rules = false, "
        "mcp_elicitations = true, request_permissions = false, skill_approval = false } }",
        "check_for_update_on_startup = false",
        f'web_search = "{web_search}"',
        "",
        "[analytics]",
        "enabled = false",
        "",
        "[feedback]",
        "enabled = false",
        "",
        "[otel]",
        'exporter = "none"',
        "log_user_prompt = false",
        "",
        "[history]",
        'persistence = "none"',
        "",
        "[features]",
        *(f"{name} = false" for name in _FEATURES_OFF),
        "",
        '[projects."/work"]',
        'trust_level = "trusted"',
        "",
        "[model_providers.datalab]",
        'name = "U-M GPT (through DataLab)"',
        'base_url = "http://gateway/v1"',
        f'env_key = "{TOKEN_ENV}"',
        'wire_api = "responses"',
        "request_max_retries = 2",
        "stream_max_retries = 2",
        "stream_idle_timeout_ms = 300000",
    ]
    if kind == "data":
        lines += [
            "",
            "[mcp_servers.ihs-data]",
            'url = "http://gateway/mcp"',
            f'bearer_token_env_var = "{TOKEN_ENV}"',
            "startup_timeout_sec = 20",
            f"tool_timeout_sec = {tool_timeout_seconds}",
            'default_tools_approval_mode = "approve"',
        ]
    return "\n".join(lines) + "\n"
